ALTER TABLE dbo.SOCIETE ADD
	REPORT_PROPRIETE_SOCIETE bit NULL DEFAULT 0
GO

--------------------------------------------------------

ALTER VIEW [dbo].[VUE_SOCIETE]
AS
SELECT        dbo.SOCIETE.ID_SOCIETE, dbo.SOCIETE.ID_SOCIETE AS SOCIETE_ID, dbo.SOCIETE.ABONNE_ID, dbo.SOCIETE.NOM_SOCIETE, dbo.SOCIETE.ADRESSE_LIGNE1_SOCIETE, dbo.SOCIETE.ADRESSE_LIGNE2_SOCIETE, 
                         dbo.SOCIETE.VILLE_SOCIETE, dbo.SOCIETE.PAYS_SOCIETE_ID, dbo.SOCIETE.TELEPHONE_SOCIETE, dbo.SOCIETE.FAX_SOCIETE, dbo.SOCIETE.EMAIL_SOCIETE, dbo.SOCIETE.SITE_WEB_SOCIETE, 
                         dbo.SOCIETE.MATRICULE_FISCAL_SOCIETE, dbo.SOCIETE.REGISTRE_COMMERCE_SOCIETE, dbo.SOCIETE.RIB_SOCIETE, dbo.SOCIETE.BANQUE_SOCIETE, dbo.SOCIETE.LOGO_SOCIETE, dbo.SOCIETE.DEVISE_SOCIETE_ID, 
                         dbo.SOCIETE.DEPOT_SOCIETE_ID, dbo.SOCIETE.GESTION_STOCK, dbo.SOCIETE.STOCK_ZERO_NEGATIF, dbo.SOCIETE.USER_CREATION_ID, dbo.SOCIETE.DATE_CREATION, dbo.SOCIETE.USER_MODIF_ID, 
                         dbo.SOCIETE.DATE_MODIF, dbo.DEVISE_BASE.NOM_DEVISE, dbo.PAYS.NOM_PAYS, dbo.DEPOT.NOM_DEPOT, dbo.DEVISE_BASE.NOMBRE_DECIMAL, dbo.SOCIETE.TIMBRE_SOCIETE, dbo.DEVISE_BASE.LIBELLE_DEVISE, 
                         dbo.SOCIETE.VISIBILITE_MENU_SOCIETE, dbo.SOCIETE.FODEC_ACHAT_SOCIETE, dbo.SOCIETE.FODEC_VENTE_SOCIETE, dbo.SOCIETE.TVA_SOCIETE_ID, dbo.SOCIETE.MAJ_PRIX_ACHAT_SOCIETE, 
                         dbo.SOCIETE.MAJ_MARGE_SOCIETE, dbo.SOCIETE.MARGE_SOCIETE, dbo.SOCIETE.CLIENT_SOCIETE_ID, dbo.TVA_ARTICLE.TAUX_TVA_ARTICLE, dbo.SOCIETE.TYPE_CALCUL_SOCIETE, dbo.CLIENT.NOM_CLIENT, 
                         dbo.SOCIETE.CLIENT_ETATIQUE_SOCIETE, dbo.SOCIETE.FOURNISSEUR_SOCIETE_ID, dbo.FOURNISSEUR.NOM_FOURNISSEUR, dbo.FOURNISSEUR.NUMERO_FOURNISSEUR, dbo.CLIENT.NUMERO_CLIENT, 
                         dbo.SOCIETE.MAJ_PRIX_VENTE_SOCIETE, dbo.SOCIETE.MODELE_IMPRESSION_DC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BCC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BLC_SOCIETE_ID, 
                         dbo.SOCIETE.MODELE_IMPRESSION_FCC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BRC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_AC_SOCIETE_ID, 
                         dbo.SOCIETE.MODELE_IMPRESSION_BCF_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BRF_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_FCF_SOCIETE_ID, 
                         dbo.SOCIETE.MODELE_IMPRESSION_BTF_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_AF_SOCIETE_ID, M1.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_DC, 
                         M2.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BCC, M3.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BLC, M4.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_FCC, 
                         M5.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BRC, M6.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_AC, M7.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BCF, 
                         M8.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BRF, M9.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_FCF, M10.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BTF, 
                         M11.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_AF, dbo.SOCIETE.QUANTITE_ARTICLE_SOCIETE, dbo.SOCIETE.PRIX_ACHAT_SOCIETE, dbo.SOCIETE.RETENUE_SOURCE_SOCIETE_ID, 
                         dbo.SOCIETE.SIGNATURE_DC_SOCIETE, dbo.SOCIETE.SIGNATURE_BCC_SOCIETE, dbo.SOCIETE.SIGNATURE_BLC_SOCIETE, dbo.SOCIETE.SIGNATURE_FCC_SOCIETE, dbo.SOCIETE.SIGNATURE_BRC_SOCIETE, 
                         dbo.SOCIETE.SIGNATURE_AC_SOCIETE, dbo.SOCIETE.SIGNATURE_SOCIETE, dbo.SOCIETE.CHOIX_MODELE_IMPRESSION_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_DC_SOCIETE, 
                         dbo.SOCIETE.CONDITION_IMPRESSION_BCC_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_BLC_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_FCC_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_BRC_SOCIETE, 
                         dbo.SOCIETE.CONDITION_IMPRESSION_AC_SOCIETE, dbo.RETENUE_SOURCE.POURCENTAGE_RS, dbo.SOCIETE.UNITE_ARTICLE_SOCIETE_ID, dbo.SOCIETE.FAMILLE_ARTICLE_SOCIETE_ID, 
                         dbo.SOCIETE.MARQUE_ARTICLE_SOCIETE_ID, dbo.SOCIETE.CATEGORIE_ARTICLE_SOCIETE_ID, dbo.UNITE_ARTICLE.NOM_UNITE_ARTICLE, dbo.FAMILLE_ARTICLE.NOM_FAMILLE_ARTICLE, 
                         dbo.MARQUE_ARTICLE.NOM_MARQUE_ARTICLE, dbo.CATEGORIE_ARTICLE.NOM_CATEGORIE_ARTICLE, dbo.SOCIETE.GARANTIE_MOIS_ARTICLE_SOCIETE, dbo.SOCIETE.TPE_ACHAT_SOCIETE, 
                         dbo.SOCIETE.TPE_VENTE_SOCIETE, dbo.SOCIETE.CLIENT_CAISSE_SOCIETE_ID, dbo.SOCIETE.ENTETE_DOCUMENT_DC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_DC_SOCIETE, 
                         dbo.SOCIETE.ENTETE_DOCUMENT_BCC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_BCC_SOCIETE, dbo.SOCIETE.ENTETE_DOCUMENT_BLC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_BLC_SOCIETE, 
                         dbo.SOCIETE.ENTETE_DOCUMENT_FCC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_FCC_SOCIETE, dbo.SOCIETE.ENTETE_DOCUMENT_BRC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_BRC_SOCIETE, 
                         dbo.SOCIETE.ENTETE_DOCUMENT_AC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_AC_SOCIETE, dbo.SOCIETE.TYPE_TRANSFERT_CAISSE_SOCIETE, dbo.SOCIETE.NBR_JOUR_ARCHIVE_TICKET_CAISSE_SOCIETE, 
                         C.NOM_CLIENT AS NOM_CLIENT_CAISSE, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_DC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BCC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BLC, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_FCC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_AC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_DF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BCF, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BRF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_FCF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_AF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BRC, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_ES, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_SS, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BTF, dbo.SOCIETE.FACTURE_CLIENT_STOCK, 
                         dbo.SOCIETE.FACTURE_FOURNISSEUR_STOCK, dbo.SOCIETE.AVOIR_FOURNISSEUR_STOCK, dbo.SOCIETE.AVOIR_CLIENT_STOCK, dbo.SOCIETE.REINITIALISER_PARAM_CAISSE_SOCIETE, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_SOURCE, dbo.SOCIETE.CODE_BARRE_NUM_AUTO_SOCIETE, dbo.SOCIETE.CODE_BARRE_INIT_AUTO_SOCIETE, dbo.SOCIETE.NUMERO_SERIE_OBLIGATOIRE_SOCIETE, 
                         dbo.SOCIETE.DESCRIPTION_SOCIETE, dbo.SOCIETE.GSM_SOCIETE, dbo.SOCIETE.DESCRIPTION_NOTE_HONORAIRE_SOCIETE, dbo.SOCIETE.NUMERO_SERIE_UNIQUE_SOCIETE, 
                         dbo.SOCIETE.TYPE_CALCUL_ARRONDISSEMENT_SOCIETE, dbo.SOCIETE.CALCUL_BENEFICE_SOCIETE, dbo.SOCIETE.REPORT_PROPRIETE_SOCIETE
FROM            dbo.SOCIETE INNER JOIN
                         dbo.DEPOT ON dbo.SOCIETE.DEPOT_SOCIETE_ID = dbo.DEPOT.ID_DEPOT AND dbo.SOCIETE.ID_SOCIETE = dbo.DEPOT.SOCIETE_ID INNER JOIN
                         dbo.DEVISE ON dbo.SOCIETE.DEVISE_SOCIETE_ID = dbo.DEVISE.ID_DEVISE AND dbo.SOCIETE.ID_SOCIETE = dbo.DEVISE.SOCIETE_ID INNER JOIN
                         dbo.DEVISE_BASE ON dbo.DEVISE.DEVISE_DEVISE_ID = dbo.DEVISE_BASE.ID_DEVISE_BASE LEFT OUTER JOIN
                         dbo.PAYS ON dbo.SOCIETE.PAYS_SOCIETE_ID = dbo.PAYS.ID_PAYS LEFT OUTER JOIN
                         dbo.TVA_ARTICLE ON dbo.TVA_ARTICLE.ID_TVA_ARTICLE = dbo.SOCIETE.TVA_SOCIETE_ID LEFT OUTER JOIN
                         dbo.CLIENT ON dbo.CLIENT.ID_CLIENT = dbo.SOCIETE.CLIENT_SOCIETE_ID LEFT OUTER JOIN
                         dbo.FOURNISSEUR ON dbo.FOURNISSEUR.ID_FOURNISSEUR = dbo.SOCIETE.FOURNISSEUR_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M1 ON M1.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_DC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M2 ON M2.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BCC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M3 ON M3.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BLC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M4 ON M4.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_FCC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M5 ON M5.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BRC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M6 ON M6.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_AC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M7 ON M7.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BCF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M8 ON M8.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BRF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M9 ON M9.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_FCF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M10 ON M10.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BTF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M11 ON M11.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_AF_SOCIETE_ID LEFT OUTER JOIN
                         dbo.RETENUE_SOURCE ON dbo.RETENUE_SOURCE.ID_RS = dbo.SOCIETE.RETENUE_SOURCE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.UNITE_ARTICLE ON dbo.UNITE_ARTICLE.ID_UNITE_ARTICLE = dbo.SOCIETE.UNITE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.FAMILLE_ARTICLE ON dbo.FAMILLE_ARTICLE.ID_FAMILLE_ARTICLE = dbo.SOCIETE.FAMILLE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.MARQUE_ARTICLE ON dbo.MARQUE_ARTICLE.ID_MARQUE_ARTICLE = dbo.SOCIETE.MARQUE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.CATEGORIE_ARTICLE ON dbo.CATEGORIE_ARTICLE.ID_CATEGORIE_ARTICLE = dbo.SOCIETE.CATEGORIE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.CLIENT AS C ON C.ID_CLIENT = dbo.SOCIETE.CLIENT_CAISSE_SOCIETE_ID
GO

--------------------------------------------------------------------

insert CONTROLE  (ID_CTRL,PAGE_ID,ID_DESIGN_CTRL,VALEUR_DEFAUT_CTRL,LISTE_DDL,VALEUR_VIDE_CTRL,CHAMPS_CALCULE_CTRL,MODIFIABLE_INSERT_CTRL,MODIFIABLE_UPDATE_CTRL,CHAMPS_CACHE_CTRL,MONNAIE_CTRL,TRONQUER_ZERO_CTRL,CHAMPS_CTRL) values (999,'65','C114','0',NULL,NULL,'0','1','1','0','0','0','REPORT_PROPRIETE_SOCIETE')
GO


-----------------------------------------------------------------------------

insert CONTROLE  (PAGE_ID,ID_DESIGN_CTRL,VALEUR_DEFAUT_CTRL,LISTE_DDL,VALEUR_VIDE_CTRL,CHAMPS_CALCULE_CTRL,MODIFIABLE_INSERT_CTRL,MODIFIABLE_UPDATE_CTRL,CHAMPS_CACHE_CTRL,MONNAIE_CTRL,TRONQUER_ZERO_CTRL,CHAMPS_CTRL) values (999,'65','C114','0',NULL,NULL,'0','1','1','0','0','0','REPORT_PROPRIETE_SOCIETE')
