ALTER TABLE dbo.SOCIETE ADD
	TYPE_CALCUL_ARRONDISSEMENT_SOCIETE varchar(50) NOT NULL CONSTRAINT DF_SOCIETE_TYPE_CALCUL_ARRONDISSEMENT_SOCIETE DEFAULT 'PAR LIGNE'
GO


-----------------------------------------------------------------------------------------------

ALTER TABLE dbo.AVOIR_CLIENT_LIGNE ADD
	TYPE_REMISE_AC_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.AVOIR_FOURNISSEUR_LIGNE ADD
	TYPE_REMISE_AF_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.BON_COMMANDE_CLIENT_LIGNE ADD
	TYPE_REMISE_BCC_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.BON_COMMANDE_FOURNISSEUR_LIGNE ADD
	TYPE_REMISE_BCF_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.BON_LIVRAISON_CLIENT_LIGNE ADD
	TYPE_REMISE_BLC_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.BON_RECEPTION_FOURNISSEUR_LIGNE ADD
	TYPE_REMISE_BRF_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.BON_RETOUR_CLIENT_LIGNE ADD
	TYPE_REMISE_BRC_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.BON_RETOUR_FOURNISSEUR_LIGNE ADD
	TYPE_REMISE_BTF_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.DEVIS_CLIENT_LIGNE ADD
	TYPE_REMISE_DC_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.FACTURE_CLIENT_LIGNE ADD
	TYPE_REMISE_FCC_L char(1) NULL DEFAULT 'M'
GO
ALTER TABLE dbo.FACTURE_FOURNISSEUR_LIGNE ADD
	TYPE_REMISE_FCF_L char(1) NULL DEFAULT 'M'
GO

----------------------------------------------------------------------------------------------

ALTER TABLE dbo.AVOIR_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_AC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.AVOIR_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_AF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_COMMANDE_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_BCC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_COMMANDE_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_BCF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_LIVRAISON_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_BLC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_RECEPTION_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_BRF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_RETOUR_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_BRC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_RETOUR_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_BTF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.DEVIS_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.FACTURE_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_FCC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.FACTURE_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_FCF_L decimal(18,3) NULL
GO

---------------------------------------------------------------------------------------------

update dbo.AVOIR_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_AC_L =TOTAL_ARTICLE_HT_BRUT_AC_L-TOTAL_ARTICLE_HT_NET_AC_L
GO
update dbo.AVOIR_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_AF_L =TOTAL_ARTICLE_HT_BRUT_AF_L-TOTAL_ARTICLE_HT_NET_AF_L
GO
update dbo.BON_COMMANDE_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_BCC_L =TOTAL_ARTICLE_HT_BRUT_BCC_L-TOTAL_ARTICLE_HT_NET_BCC_L
GO
update dbo.BON_COMMANDE_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_BCF_L =TOTAL_ARTICLE_HT_BRUT_BCF_L-TOTAL_ARTICLE_HT_NET_BCF_L
GO
update dbo.BON_LIVRAISON_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_BLC_L =TOTAL_ARTICLE_HT_BRUT_BLC_L-TOTAL_ARTICLE_HT_NET_BLC_L
GO
update dbo.BON_RECEPTION_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_BRF_L =TOTAL_ARTICLE_HT_BRUT_BRF_L-TOTAL_ARTICLE_HT_NET_BRF_L
GO
update dbo.BON_RETOUR_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_BRC_L =TOTAL_ARTICLE_HT_BRUT_BRC_L-TOTAL_ARTICLE_HT_NET_BRC_L
GO
update dbo.BON_RETOUR_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_BTF_L =TOTAL_ARTICLE_HT_BRUT_BTF_L-TOTAL_ARTICLE_HT_NET_BTF_L
GO
update dbo.DEVIS_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_DC_L =TOTAL_ARTICLE_HT_BRUT_DC_L-TOTAL_ARTICLE_HT_NET_DC_L
GO
update dbo.FACTURE_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_FCC_L =TOTAL_ARTICLE_HT_BRUT_FCC_L-TOTAL_ARTICLE_HT_NET_FCC_L
GO
update dbo.FACTURE_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_FCF_L =TOTAL_ARTICLE_HT_BRUT_FCF_L-TOTAL_ARTICLE_HT_NET_FCF_L
GO
----------------------------------------------------------------------------------------------

ALTER TABLE dbo.AVOIR_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_AC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.AVOIR_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_AF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_COMMANDE_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_BCC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_COMMANDE_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_BCF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_LIVRAISON_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_BLC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_RECEPTION_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_BRF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_RETOUR_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_BRC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.BON_RETOUR_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_BTF_L decimal(18,3) NULL
GO
ALTER TABLE dbo.DEVIS_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_DC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.FACTURE_CLIENT_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_FCC_L decimal(18,3) NULL
GO
ALTER TABLE dbo.FACTURE_FOURNISSEUR_LIGNE ADD
	TOTAL_ARTICLE_REMISE_DEVISE_FCF_L decimal(18,3) NULL
GO


----------------------------------------------------------------------------------------------

update dbo.AVOIR_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_AC_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_AC_L-TOTAL_ARTICLE_HT_NET_DEVISE_AC_L
GO
update dbo.AVOIR_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_AF_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_AF_L-TOTAL_ARTICLE_HT_NET_DEVISE_AF_L
GO
update dbo.BON_COMMANDE_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_BCC_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_BCC_L-TOTAL_ARTICLE_HT_NET_DEVISE_BCC_L
GO
update dbo.BON_COMMANDE_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_BCF_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_BCF_L-TOTAL_ARTICLE_HT_NET_DEVISE_BCF_L
GO
update dbo.BON_LIVRAISON_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_BLC_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_BLC_L-TOTAL_ARTICLE_HT_NET_DEVISE_BLC_L
GO
update dbo.BON_RECEPTION_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_BRF_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_BRF_L-TOTAL_ARTICLE_HT_NET_DEVISE_BRF_L
GO
update dbo.BON_RETOUR_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_BRC_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_BRC_L-TOTAL_ARTICLE_HT_NET_DEVISE_BRC_L
GO
update dbo.BON_RETOUR_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_BTF_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_BTF_L-TOTAL_ARTICLE_HT_NET_DEVISE_BTF_L
GO
update dbo.DEVIS_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_DC_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_DC_L-TOTAL_ARTICLE_HT_NET_DEVISE_DC_L
GO
update dbo.FACTURE_CLIENT_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_FCC_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_FCC_L-TOTAL_ARTICLE_HT_NET_DEVISE_FCC_L
GO
update dbo.FACTURE_FOURNISSEUR_LIGNE set
	TOTAL_ARTICLE_REMISE_DEVISE_FCF_L =TOTAL_ARTICLE_HT_BRUT_DEVISE_FCF_L-TOTAL_ARTICLE_HT_NET_DEVISE_FCF_L
GO

----------------------------------------------------------------------------------------------

ALTER PROCEDURE [dbo].[PRC_AJOUTER_MODIFIER_DOCUMENT_LIGNE]
  @ID_TYPE_DOCUMENT numeric(18,0)
, @TABLE varchar(50)
, @TABLE_LIGNE varchar(50)
, @ABBREVIATION varchar(10)
, @ID_DEVISE numeric(18,0)
, @ID numeric(18,0)
, @ID_L numeric(18,0)
, @NOMBRE_DECIMAL_SOCIETE int
, @NOMBRE_DECIMAL int
, @TAUX_REMISE_NEW decimal(5,2)
, @MONTANT_REMISE_NEW decimal(18,3)
, @TAUX_REMISE_OLD decimal(5,2)
, @MONTANT_REMISE_OLD decimal(18,3)
, @PRIX_ARTICLE_HT_BRUT_L decimal(18,3)
, @ID_SOCIETE numeric(18,0)
, @TAUX_CHANGE decimal(20,5)
, @QUANTITE decimal(18,5)
, @VA varchar(10)
, @PRIX_TTC decimal(18,3)
, @PRIX_HT decimal(18,3)

AS
BEGIN

declare @sql nvarchar(MAX)
declare @ID_DEPOT numeric(18,0)
declare @NOM_DEPOT varchar(50)
declare @PRIX_TTC_OLD decimal(18,3)
declare @ORDRE int
declare @N int
declare @NUMERO_SERIE varchar(100)
declare @STATUT_NS varchar(50)
declare @BENEFICE_TD bit
declare @BENEFICE decimal(38,3)
declare @ARRONDISSEMENT char(1)


select @ARRONDISSEMENT=TYPE_CALCUL_ARRONDISSEMENT_SOCIETE from SOCIETE where ID_SOCIETE=@ID_SOCIETE

--Contrôle pour éviter l'insertion des données dans ID (Article,Dépôt)
set @sql='select @N=count(1) from '+@TABLE_LIGNE+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
+' and ((DEPOT_'+@ABBREVIATION+'_L_ID is NULL and NOM_DEPOT_'+@ABBREVIATION+'_L is NOT NULL)'
+' or (DEPOT_'+@ABBREVIATION+'_L_ID is NOT NULL and NOM_DEPOT_'+@ABBREVIATION+'_L is NULL)'
+' or (ARTICLE_'+@ABBREVIATION+'_L_ID is NULL and (ARTICLE_CODE_'+@ABBREVIATION+'_L is NOT NULL or LIBELLE_ARTICLE_'+@ABBREVIATION+'_L is NOT NULL))'
+' or (ARTICLE_CODE_'+@ABBREVIATION+'_L is NULL and (ARTICLE_'+@ABBREVIATION+'_L_ID is NOT NULL or LIBELLE_ARTICLE_'+@ABBREVIATION+'_L is NOT NULL))'
+' or (LIBELLE_ARTICLE_'+@ABBREVIATION+'_L is NULL and (ARTICLE_'+@ABBREVIATION+'_L_ID is NOT NULL or ARTICLE_CODE_'+@ABBREVIATION+'_L is NOT NULL)))'
execute sp_executesql @sql,N'@N int output',@N output
if @N>0
	Begin
		ROLLBACK TRANSACTION
		insert SQL_ERREUR (QUERY) values (@sql)
		select -99 as RESULTAT,ERROR_NUMBER() 
		RETURN
	End

select @STATUT_NS=STATUT_NUMERO_SERIE_TD,@BENEFICE_TD=BENEFICE_TD from TYPE_DOCUMENT where ID_TD=@ID_TYPE_DOCUMENT

--FORCER LA QUANTITE A 1 QUAND EXISTE NUMERO DE SERIE
if @STATUT_NS is not NULL
	Begin
		set @sql='select @NUMERO_SERIE=NUMERO_SERIE_'+@ABBREVIATION+'_L from '+@TABLE_LIGNE+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @sql,N'@NUMERO_SERIE varchar(100) output',@NUMERO_SERIE output
		if ISNULL(@NUMERO_SERIE,'')<>'' and ISNULL(@QUANTITE,0)<>1
			Begin
				set @sql='update '+@TABLE_LIGNE+' set QTE_ARTICLE_'+@ABBREVIATION+'_L=1 where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
				execute sp_executesql @sql
			End
	End


BEGIN TRANSACTION

BEGIN TRY

set @sql='select @ORDRE=ORDRE_'+@ABBREVIATION+'_L from '+@TABLE_LIGNE+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
execute sp_executesql @sql,N'@ORDRE int output',@ORDRE output

if @ORDRE is NULL
	Begin
		set @sql='select @ORDRE=isnull(max(ORDRE_'+@ABBREVIATION+'_L),0) from '+@TABLE_LIGNE+' where '+@ABBREVIATION+'_ID='+CAST(@ID as varchar(50))
		execute sp_executesql @sql,N'@ORDRE int output',@ORDRE output
		set @sql='update '+@TABLE_LIGNE+' set ORDRE_'+@ABBREVIATION+'_L='+CAST(@ORDRE+1 as varchar(50))+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @sql
	End

if @PRIX_TTC=0
	if ISNULL(@MONTANT_REMISE_NEW,0)<>ISNULL(@MONTANT_REMISE_OLD,0) and ISNULL(@TAUX_REMISE_NEW,0)=ISNULL(@TAUX_REMISE_OLD,0)
		if @PRIX_ARTICLE_HT_BRUT_L=0
			Begin
				set @sql='UPDATE '+@TABLE_LIGNE+' set
					TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L=0
					where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
				execute sp_executesql @SQL
			End
		else
			Begin
				set @sql='UPDATE '+@TABLE_LIGNE+' set
					TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L=ROUND(ISNULL(MONTANT_REMISE_ARTICLE_'+@ABBREVIATION+'_L,0)*100/PRIX_'+@VA+'_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L,2),
					TYPE_REMISE_'+@ABBREVIATION+'_L=''M'' '
					+ ' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
				execute sp_executesql @SQL
			End
	else
		Begin
			set @sql='UPDATE '+@TABLE_LIGNE+' set
				MONTANT_REMISE_ARTICLE_'+@ABBREVIATION+'_L=ROUND(ISNULL(PRIX_'+@VA+'_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L,0)*ISNULL(TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L,0)/100,'+CAST(@NOMBRE_DECIMAL as varchar(50))+'),
				TYPE_REMISE_'+@ABBREVIATION+'_L=''P'' '
				+ ' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
			execute sp_executesql @SQL
		End
else
	Begin
		set @sql='UPDATE '+@TABLE_LIGNE+' set
			TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L=0,
			MONTANT_REMISE_ARTICLE_'+@ABBREVIATION+'_L=0,
			FODEC_'+@ABBREVIATION+'_L=0,
			TPE_'+@ABBREVIATION+'_L=0,
			TAXE_ENERGIE_'+@ABBREVIATION+'_L=0,
			TYPE_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L=NULL,
			VALEUR_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L=0 '
			+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @SQL
	End

if @PRIX_TTC=1
	Begin
		set @sql='UPDATE '+@TABLE_LIGNE+' set
		PRIX_'+@VA+'_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L=ROUND(ISNULL(PRIX_'+@VA+'_ARTICLE_TTC_'+@ABBREVIATION+'_L,0)/(1+ISNULL(TAUX_ARTICLE_TVA_'+@ABBREVIATION+'_L,0)/100),'+CAST(@NOMBRE_DECIMAL as varchar(50))+') 
		where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @SQL
	End

set @sql='UPDATE '+@TABLE_LIGNE+' set
PRIX_'+@VA+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L=ROUND(ISNULL(PRIX_'+@VA+'_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L,0),'+CAST(@NOMBRE_DECIMAL as varchar(50))+')-ISNULL(MONTANT_REMISE_ARTICLE_'+@ABBREVIATION+'_L,0)
where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
execute sp_executesql @SQL


set @sql='UPDATE '+@TABLE_LIGNE+' set
MONTANT_ARTICLE_TVA_'+@ABBREVIATION+'_L=ROUND(ISNULL(PRIX_'+@VA+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L,0)*ISNULL(TAUX_ARTICLE_TVA_'+@ABBREVIATION+'_L,0)/100,'+CAST(@NOMBRE_DECIMAL as varchar(50))+'),
DROIT_CONSOMMATION_'+@ABBREVIATION+'_L=CASE WHEN TYPE_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L=''UNITE'' THEN VALEUR_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L'
+ ' WHEN TYPE_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L=''% PRIX'' THEN ROUND(PRIX_'+@VA+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L*VALEUR_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L/100,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')  ELSE NULL END '
+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
execute sp_executesql @SQL

set @sql='UPDATE '+@TABLE_LIGNE+' set '
if @PRIX_TTC=0
	set @sql=@sql+'PRIX_'+@VA+'_ARTICLE_TTC_'+@ABBREVIATION+'_L=ISNULL(PRIX_'+@VA+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L,0)+ISNULL(MONTANT_ARTICLE_TVA_'+@ABBREVIATION+'_L,0),'
set @sql=@sql+'TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L=ROUND(ISNULL(QTE_ARTICLE_'+@ABBREVIATION+'_L,0)*ISNULL(PRIX_'+@VA+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L,0),'+CAST(@NOMBRE_DECIMAL as varchar(50))+'),
TOTAL_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L=ROUND(ISNULL(QTE_ARTICLE_'+@ABBREVIATION+'_L,0)*ISNULL(PRIX_'+@VA+'_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L,0),'+CAST(@NOMBRE_DECIMAL as varchar(50))+'),
TOTAL_ARTICLE_REMISE_'+@ABBREVIATION+'_L=ROUND(ISNULL(QTE_ARTICLE_'+@ABBREVIATION+'_L,0)*ISNULL(MONTANT_REMISE_ARTICLE_'+@ABBREVIATION+'_L,0),'+CAST(@NOMBRE_DECIMAL as varchar(50))+')
where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
execute sp_executesql @SQL

set @sql='UPDATE '+@TABLE_LIGNE+' set
TOTAL_ARTICLE_FODEC_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L*(ISNULL(FODEC_'+@ABBREVIATION+'_L,0)/100),'+CAST(@NOMBRE_DECIMAL as varchar(50))+'),
TOTAL_ARTICLE_TPE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L*(ISNULL(TPE_'+@ABBREVIATION+'_L,0)/100),'+CAST(@NOMBRE_DECIMAL as varchar(50))+'),
TOTAL_ARTICLE_TAXE_ENERGIE_'+@ABBREVIATION+'_L=ROUND(ISNULL(TAXE_ENERGIE_'+@ABBREVIATION+'_L,0)*ISNULL(QTE_ARTICLE_'+@ABBREVIATION+'_L,0),'+CAST(@NOMBRE_DECIMAL as varchar(50))+'),
TOTAL_ARTICLE_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L=ISNULL(DROIT_CONSOMMATION_'+@ABBREVIATION+'_L*ISNULL(QTE_ARTICLE_'+@ABBREVIATION+'_L,0),0),
TOTAL_ARTICLE_ASSIETTE_TVA_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L*(1+(ISNULL(FODEC_'+@ABBREVIATION+'_L,0)+ISNULL(TPE_'+@ABBREVIATION+'_L,0))/100)+ISNULL(TAXE_ENERGIE_'+@ABBREVIATION+'_L,0)*ISNULL(QTE_ARTICLE_'+@ABBREVIATION+'_L,0)+ISNULL(DROIT_CONSOMMATION_'+@ABBREVIATION+'_L,0)*ISNULL(QTE_ARTICLE_'+@ABBREVIATION+'_L,0),'+CAST(@NOMBRE_DECIMAL as varchar(50))+')
where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
execute sp_executesql @SQL

--if (@PRIX_TTC=0 and @PRIX_HT=1) 
if @PRIX_TTC=0
	Begin
		set @sql='UPDATE '+@TABLE_LIGNE+' set
		TOTAL_ARTICLE_TVA_'+@ABBREVIATION+'_L=ROUND(ISNULL(TOTAL_ARTICLE_ASSIETTE_TVA_'+@ABBREVIATION+'_L,0)*ISNULL(TAUX_ARTICLE_TVA_'+@ABBREVIATION+'_L,0)/100,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')
		where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @SQL
		
		set @sql='UPDATE '+@TABLE_LIGNE+' set '
		set @sql=@sql+'TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L=TOTAL_ARTICLE_ASSIETTE_TVA_'+@ABBREVIATION+'_L+TOTAL_ARTICLE_TVA_'+@ABBREVIATION+'_L'
		set @sql=@sql+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @SQL
	End
else
	Begin
		set @sql='UPDATE '+@TABLE_LIGNE+' set '
		set @sql=@sql+'TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L=ROUND(PRIX_'+@VA+'_ARTICLE_TTC_'+@ABBREVIATION+'_L*isnull(QTE_ARTICLE_'+@ABBREVIATION+'_L,0),'+CAST(@NOMBRE_DECIMAL as varchar(50))+') '
		set @sql=@sql+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @SQL

		set @sql='UPDATE '+@TABLE_LIGNE+' set
		TOTAL_ARTICLE_TVA_'+@ABBREVIATION+'_L=TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L-TOTAL_ARTICLE_ASSIETTE_TVA_'+@ABBREVIATION+'_L'
		+' where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @SQL
	End


set @sql=';With CTE as (select 
sum(isnull(TOTAL_ARTICLE_TVA_'+@ABBREVIATION+'_L,0)) as MONTANT_TVA,
sum(isnull(TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L,0)) as MONTANT_HT_NET,
sum(isnull(TOTAL_ARTICLE_REMISE_'+@ABBREVIATION+'_L,0)) as MONTANT_REMISE,
sum(isnull(TOTAL_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L,0)) as MONTANT_HT_BRUT,
sum(isnull(TOTAL_ARTICLE_FODEC_'+@ABBREVIATION+'_L,0)) as MONTANT_FODEC,
sum(isnull(TOTAL_ARTICLE_TPE_'+@ABBREVIATION+'_L,0)) as MONTANT_TPE,
sum(isnull(TOTAL_ARTICLE_TAXE_ENERGIE_'+@ABBREVIATION+'_L,0)) as MONTANT_TAXE_ENERGIE,
sum(isnull(TOTAL_ARTICLE_DROIT_CONSOMMATION_'+@ABBREVIATION+'_L,0)) as MONTANT_DROIT_CONSOMMATION,
sum(isnull(TOTAL_ARTICLE_ASSIETTE_TVA_'+@ABBREVIATION+'_L,0)) as MONTANT_ASSIETTE_TVA,
sum(isnull(TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L,0)) as MONTANT_TTC,
sum(isnull(QTE_ARTICLE_'+@ABBREVIATION+'_L,0)) as TOTAL_QUANTITE,
sum(isnull(NOMBRE_CARTON_'+@ABBREVIATION+'_L,0)) as TOTAL_CARTON,
sum(isnull(POIDS_ARTICLE_BRUT_'+@ABBREVIATION+'_L,0)*isnull(QTE_ARTICLE_'+@ABBREVIATION+'_L,0)) as POIDS_BRUT,
sum(isnull(POIDS_ARTICLE_NET_'+@ABBREVIATION+'_L,0)*isnull(QTE_ARTICLE_'+@ABBREVIATION+'_L,0)) as POIDS_NET'
+' from '+CASE WHEN @ARRONDISSEMENT='PAR LIGNE' THEN @TABLE_LIGNE ELSE 'VUE_'+@TABLE_LIGNE+'_ARRONDISSEMENT' END+' where '+@ABBREVIATION+'_ID='+CAST(@ID as varchar(50))+') 
UPDATE '+@TABLE+' set
MONTANT_TVA_'+@ABBREVIATION+'=(select MONTANT_TVA from CTE),
MONTANT_HT_BRUT_'+@ABBREVIATION+'=(select MONTANT_HT_BRUT from CTE),
MONTANT_REMISE_'+@ABBREVIATION+'=(select MONTANT_REMISE from CTE),
MONTANT_HT_NET_'+@ABBREVIATION+'=(select MONTANT_HT_NET from CTE),
MONTANT_FODEC_'+@ABBREVIATION+'=(select MONTANT_FODEC from CTE),
MONTANT_TPE_'+@ABBREVIATION+'=(select MONTANT_TPE from CTE),
MONTANT_TAXE_ENERGIE_'+@ABBREVIATION+'=(select MONTANT_TAXE_ENERGIE from CTE),
MONTANT_DROIT_CONSOMMATION_'+@ABBREVIATION+'=(select MONTANT_DROIT_CONSOMMATION from CTE),
MONTANT_ASSIETTE_TVA_'+@ABBREVIATION+'=(select MONTANT_ASSIETTE_TVA from CTE),
MONTANT_TTC_'+@ABBREVIATION+'=(select MONTANT_TTC from CTE),
TOTAL_QUANTITE_'+@ABBREVIATION+'=(select TOTAL_QUANTITE from CTE),
NOMBRE_CARTON_'+@ABBREVIATION+'=(select CASE WHEN TOTAL_CARTON=0 THEN NULL ELSE TOTAL_CARTON END from CTE),
POIDS_BRUT_'+@ABBREVIATION+'=(select CASE WHEN POIDS_BRUT=0 THEN POIDS_BRUT_'+@ABBREVIATION+' ELSE POIDS_BRUT END from CTE),
POIDS_NET_'+@ABBREVIATION+'=(select CASE WHEN POIDS_NET=0 THEN POIDS_NET_'+@ABBREVIATION+' ELSE POIDS_NET END from CTE)'

set @sql=@sql+' where ID_'+@ABBREVIATION+'='+CAST(@ID as varchar(50))

execute sp_executesql @SQL

set @sql='UPDATE '+@TABLE+' set
NET_PAYER_'+@ABBREVIATION+'=MONTANT_TTC_'+@ABBREVIATION+'+MONTANT_TIMBRE_'+@ABBREVIATION+
',MONTANT_REMISE_'+@ABBREVIATION+'=MONTANT_HT_BRUT_'+@ABBREVIATION+'-MONTANT_HT_NET_'+@ABBREVIATION+'
where ID_'+@ABBREVIATION+'='+CAST(@ID as varchar(50))
execute sp_executesql @SQL

if @ID_TYPE_DOCUMENT=8
	Begin
		set @sql=';With CTE as (select 
		sum(isnull(TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L,0)) as MONTANT_TTC'
		+' from '+@TABLE_LIGNE+' where '+@ABBREVIATION+'_ID='+CAST(@ID as varchar(50))+') 
		UPDATE '+@TABLE+' set 
		ASSIETTE_RC_'+@ABBREVIATION+'=(select MONTANT_TTC from CTE) '
		+' where ID_'+@ABBREVIATION+'='+CAST(@ID as varchar(50))
		execute sp_executesql @sql
	End

if @ID_DEVISE<>0
	Begin
		set @sql='update '+@TABLE_LIGNE+' set
		PRIX_'+@VA+'_ARTICLE_HT_BRUT_DEVISE_'+@ABBREVIATION+'_L=ROUND(PRIX_'+@VA+'_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_REMISE_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_REMISE_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		PRIX_'+@VA+'_ARTICLE_HT_NET_DEVISE_'+@ABBREVIATION+'_L=ROUND(PRIX_'+@VA+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_ARTICLE_TVA_DEVISE_'+@ABBREVIATION+'_L=ROUND(MONTANT_ARTICLE_TVA_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		PRIX_'+@VA+'_ARTICLE_TTC_DEVISE_'+@ABBREVIATION+'_L=ROUND(PRIX_'+@VA+'_ARTICLE_TTC_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_TVA_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_TVA_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_HT_NET_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_HT_BRUT_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_FODEC_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_FODEC_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_TPE_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_TPE_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_TAXE_ENERGIE_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_TAXE_ENERGIE_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_ASSIETTE_TVA_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_ASSIETTE_TVA_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		TOTAL_ARTICLE_TTC_DEVISE_'+@ABBREVIATION+'_L=ROUND(TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+')
		where ID_'+@ABBREVIATION+'_L='+CAST(@ID_L as varchar(50))
		execute sp_executesql @SQL

		set @sql='update '+@TABLE+' set
		MONTANT_HT_BRUT_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_HT_BRUT_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_REMISE_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_REMISE_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_TVA_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_TVA_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_HT_NET_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_HT_NET_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_FODEC_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_FODEC_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_TPE_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_TPE_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_TAXE_ENERGIE_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_TAXE_ENERGIE_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_ASSIETTE_TVA_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_ASSIETTE_TVA_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_TTC_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_TTC_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		MONTANT_TIMBRE_DEVISE_'+@ABBREVIATION+'=ROUND(MONTANT_TIMBRE_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+'),
		NET_PAYER_DEVISE_'+@ABBREVIATION+'=ROUND(NET_PAYER_'+@ABBREVIATION+'*'+CAST(@TAUX_CHANGE as varchar(50))+','+CAST(@NOMBRE_DECIMAL_SOCIETE as varchar(50))+')
		where ID_'+@ABBREVIATION+'='+CAST(@ID as varchar(50))
		execute sp_executesql @SQL
	End

if @BENEFICE_TD=1
	Begin	
		set @sql='select @BENEFICE=sum(ISNULL(L.TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L,0)-
		CAST(ISNULL(A.PRIX_REVIENT_ARTICLE,0)*ISNULL(L.QTE_ARTICLE_'+@ABBREVIATION+'_L,0) as decimal(38,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')))'
		+' from '+@TABLE_LIGNE+' L '
		+' inner join VUE_ARTICLE A on A.ID_ARTICLE=L.ARTICLE_'+@ABBREVIATION+'_L_ID'
		+' where '+@ABBREVIATION+'_ID='+CAST(@ID as varchar(50))
		execute sp_executesql @sql,N'@BENEFICE decimal(18,3) output',@BENEFICE output

		set @sql='update '+@TABLE+' set '
		+ 'MONTANT_BENEFICE_'+@ABBREVIATION+'='+CAST(@BENEFICE as varchar(50))
		+ ' where ID_'+@ABBREVIATION+'='+CAST(@ID as varchar(50))
		execute sp_executesql @sql
	End

COMMIT TRANSACTION

END TRY
BEGIN CATCH  
	ROLLBACK TRANSACTION
	insert SQL_ERREUR (QUERY) values (@sql)
	select -99 as RESULTAT,ERROR_NUMBER() 
	RETURN
END CATCH;  

END

GO
--------------------------------------------------------------------------------------

create view VUE_FACTURE_CLIENT_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_FCC_L,
FCC_ID,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0) 
as TOTAL_ARTICLE_HT_BRUT_FCC_L,
CASE WHEN TYPE_REMISE_FCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCC_L,0))*ISNULL(QTE_ARTICLE_FCC_L,0)
END	
as TOTAL_ARTICLE_REMISE_FCC_L,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0)
-
CASE WHEN TYPE_REMISE_FCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCC_L,0))*ISNULL(QTE_ARTICLE_FCC_L,0)
END
as TOTAL_ARTICLE_HT_NET_FCC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0)
-
CASE WHEN TYPE_REMISE_FCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCC_L,0))*ISNULL(QTE_ARTICLE_FCC_L,0)
END)
*ISNULL(FODEC_FCC_L,0)/100
as TOTAL_ARTICLE_FODEC_FCC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0)
-
CASE WHEN TYPE_REMISE_FCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_FCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCC_L,0))*ISNULL(QTE_ARTICLE_FCC_L,0)
END)
*ISNULL(TPE_FCC_L,0)/100
as TOTAL_ARTICLE_TPE_FCC_L,
ISNULL(TAXE_ENERGIE_FCC_L,0)*ISNULL(QTE_ARTICLE_FCC_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_FCC_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_FCC_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_FCC_L
WHEN TYPE_DROIT_CONSOMMATION_FCC_L='% PRIX' THEN PRIX_VENTE_ARTICLE_HT_NET_FCC_L*VALEUR_DROIT_CONSOMMATION_FCC_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_FCC_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_FCC_L,
TAUX_ARTICLE_TVA_FCC_L,
QTE_ARTICLE_FCC_L,
NOMBRE_CARTON_FCC_L,
POIDS_ARTICLE_BRUT_FCC_L,
POIDS_ARTICLE_NET_FCC_L

from FACTURE_CLIENT_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_FCC_L+TOTAL_ARTICLE_FODEC_FCC_L+TOTAL_ARTICLE_TPE_FCC_L+TOTAL_ARTICLE_TAXE_ENERGIE_FCC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_FCC_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_FCC_L,
(TOTAL_ARTICLE_HT_BRUT_FCC_L+TOTAL_ARTICLE_FODEC_FCC_L+TOTAL_ARTICLE_TPE_FCC_L+TOTAL_ARTICLE_TAXE_ENERGIE_FCC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_FCC_L )*ISNULL(TAUX_ARTICLE_TVA_FCC_L,0)/100 
as TOTAL_ARTICLE_TVA_FCC_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_FCC_L+TOTAL_ARTICLE_TVA_FCC_L as TOTAL_ARTICLE_TTC_FCC_L
from CTE1

GO

-------------------------------------------------------------------------------------

create view VUE_FACTURE_FOURNISSEUR_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_FCF_L,
FCF_ID,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0) 
as TOTAL_ARTICLE_HT_BRUT_FCF_L,
CASE WHEN TYPE_REMISE_FCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCF_L,0))*ISNULL(QTE_ARTICLE_FCF_L,0)
END	
as TOTAL_ARTICLE_REMISE_FCF_L,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0)
-
CASE WHEN TYPE_REMISE_FCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCF_L,0))*ISNULL(QTE_ARTICLE_FCF_L,0)
END
as TOTAL_ARTICLE_HT_NET_FCF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0)
-
CASE WHEN TYPE_REMISE_FCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCF_L,0))*ISNULL(QTE_ARTICLE_FCF_L,0)
END)
*ISNULL(FODEC_FCF_L,0)/100
as TOTAL_ARTICLE_FODEC_FCF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0)
-
CASE WHEN TYPE_REMISE_FCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_FCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_FCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_FCF_L,0))*ISNULL(QTE_ARTICLE_FCF_L,0)
END)
*ISNULL(TPE_FCF_L,0)/100
as TOTAL_ARTICLE_TPE_FCF_L,
ISNULL(TAXE_ENERGIE_FCF_L,0)*ISNULL(QTE_ARTICLE_FCF_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_FCF_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_FCF_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_FCF_L
WHEN TYPE_DROIT_CONSOMMATION_FCF_L='% PRIX' THEN PRIX_ACHAT_ARTICLE_HT_NET_FCF_L*VALEUR_DROIT_CONSOMMATION_FCF_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_FCF_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_FCF_L,
TAUX_ARTICLE_TVA_FCF_L,
QTE_ARTICLE_FCF_L,
NOMBRE_CARTON_FCF_L,
POIDS_ARTICLE_BRUT_FCF_L,
POIDS_ARTICLE_NET_FCF_L

from FACTURE_FOURNISSEUR_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_FCF_L+TOTAL_ARTICLE_FODEC_FCF_L+TOTAL_ARTICLE_TPE_FCF_L+TOTAL_ARTICLE_TAXE_ENERGIE_FCF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_FCF_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_FCF_L,
(TOTAL_ARTICLE_HT_BRUT_FCF_L+TOTAL_ARTICLE_FODEC_FCF_L+TOTAL_ARTICLE_TPE_FCF_L+TOTAL_ARTICLE_TAXE_ENERGIE_FCF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_FCF_L )*ISNULL(TAUX_ARTICLE_TVA_FCF_L,0)/100 
as TOTAL_ARTICLE_TVA_FCF_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_FCF_L+TOTAL_ARTICLE_TVA_FCF_L as TOTAL_ARTICLE_TTC_FCF_L
from CTE1

GO

--------------------------------------------------------------------------------

create view VUE_BON_COMMANDE_CLIENT_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_BCC_L,
BCC_ID,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0) 
as TOTAL_ARTICLE_HT_BRUT_BCC_L,
CASE WHEN TYPE_REMISE_BCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCC_L,0))*ISNULL(QTE_ARTICLE_BCC_L,0)
END	
as TOTAL_ARTICLE_REMISE_BCC_L,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0)
-
CASE WHEN TYPE_REMISE_BCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCC_L,0))*ISNULL(QTE_ARTICLE_BCC_L,0)
END
as TOTAL_ARTICLE_HT_NET_BCC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0)
-
CASE WHEN TYPE_REMISE_BCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCC_L,0))*ISNULL(QTE_ARTICLE_BCC_L,0)
END)
*ISNULL(FODEC_BCC_L,0)/100
as TOTAL_ARTICLE_FODEC_BCC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0)
-
CASE WHEN TYPE_REMISE_BCC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BCC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCC_L,0))*ISNULL(QTE_ARTICLE_BCC_L,0)
END)
*ISNULL(TPE_BCC_L,0)/100
as TOTAL_ARTICLE_TPE_BCC_L,
ISNULL(TAXE_ENERGIE_BCC_L,0)*ISNULL(QTE_ARTICLE_BCC_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_BCC_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_BCC_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_BCC_L
WHEN TYPE_DROIT_CONSOMMATION_BCC_L='% PRIX' THEN PRIX_VENTE_ARTICLE_HT_NET_BCC_L*VALEUR_DROIT_CONSOMMATION_BCC_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_BCC_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_BCC_L,
TAUX_ARTICLE_TVA_BCC_L,
QTE_ARTICLE_BCC_L,
NOMBRE_CARTON_BCC_L,
POIDS_ARTICLE_BRUT_BCC_L,
POIDS_ARTICLE_NET_BCC_L

from BON_COMMANDE_CLIENT_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_BCC_L+TOTAL_ARTICLE_FODEC_BCC_L+TOTAL_ARTICLE_TPE_BCC_L+TOTAL_ARTICLE_TAXE_ENERGIE_BCC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BCC_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_BCC_L,
(TOTAL_ARTICLE_HT_BRUT_BCC_L+TOTAL_ARTICLE_FODEC_BCC_L+TOTAL_ARTICLE_TPE_BCC_L+TOTAL_ARTICLE_TAXE_ENERGIE_BCC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BCC_L )*ISNULL(TAUX_ARTICLE_TVA_BCC_L,0)/100 
as TOTAL_ARTICLE_TVA_BCC_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_BCC_L+TOTAL_ARTICLE_TVA_BCC_L as TOTAL_ARTICLE_TTC_BCC_L
from CTE1

GO

----------------------------------------------------------------------------


create view VUE_BON_LIVRAISON_CLIENT_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_BLC_L,
BLC_ID,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0) 
as TOTAL_ARTICLE_HT_BRUT_BLC_L,
CASE WHEN TYPE_REMISE_BLC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BLC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BLC_L,0))*ISNULL(QTE_ARTICLE_BLC_L,0)
END	
as TOTAL_ARTICLE_REMISE_BLC_L,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0)
-
CASE WHEN TYPE_REMISE_BLC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BLC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BLC_L,0))*ISNULL(QTE_ARTICLE_BLC_L,0)
END
as TOTAL_ARTICLE_HT_NET_BLC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0)
-
CASE WHEN TYPE_REMISE_BLC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BLC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BLC_L,0))*ISNULL(QTE_ARTICLE_BLC_L,0)
END)
*ISNULL(FODEC_BLC_L,0)/100
as TOTAL_ARTICLE_FODEC_BLC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0)
-
CASE WHEN TYPE_REMISE_BLC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BLC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BLC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BLC_L,0))*ISNULL(QTE_ARTICLE_BLC_L,0)
END)
*ISNULL(TPE_BLC_L,0)/100
as TOTAL_ARTICLE_TPE_BLC_L,
ISNULL(TAXE_ENERGIE_BLC_L,0)*ISNULL(QTE_ARTICLE_BLC_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_BLC_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_BLC_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_BLC_L
WHEN TYPE_DROIT_CONSOMMATION_BLC_L='% PRIX' THEN PRIX_VENTE_ARTICLE_HT_NET_BLC_L*VALEUR_DROIT_CONSOMMATION_BLC_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_BLC_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_BLC_L,
TAUX_ARTICLE_TVA_BLC_L,
QTE_ARTICLE_BLC_L,
NOMBRE_CARTON_BLC_L,
POIDS_ARTICLE_BRUT_BLC_L,
POIDS_ARTICLE_NET_BLC_L

from BON_LIVRAISON_CLIENT_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_BLC_L+TOTAL_ARTICLE_FODEC_BLC_L+TOTAL_ARTICLE_TPE_BLC_L+TOTAL_ARTICLE_TAXE_ENERGIE_BLC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BLC_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_BLC_L,
(TOTAL_ARTICLE_HT_BRUT_BLC_L+TOTAL_ARTICLE_FODEC_BLC_L+TOTAL_ARTICLE_TPE_BLC_L+TOTAL_ARTICLE_TAXE_ENERGIE_BLC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BLC_L )*ISNULL(TAUX_ARTICLE_TVA_BLC_L,0)/100 
as TOTAL_ARTICLE_TVA_BLC_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_BLC_L+TOTAL_ARTICLE_TVA_BLC_L as TOTAL_ARTICLE_TTC_BLC_L
from CTE1

GO


---------------------------------------------------------------------------------------


create view VUE_BON_RETOUR_CLIENT_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_BRC_L,
BRC_ID,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0) 
as TOTAL_ARTICLE_HT_BRUT_BRC_L,
CASE WHEN TYPE_REMISE_BRC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRC_L,0))*ISNULL(QTE_ARTICLE_BRC_L,0)
END	
as TOTAL_ARTICLE_REMISE_BRC_L,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0)
-
CASE WHEN TYPE_REMISE_BRC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRC_L,0))*ISNULL(QTE_ARTICLE_BRC_L,0)
END
as TOTAL_ARTICLE_HT_NET_BRC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0)
-
CASE WHEN TYPE_REMISE_BRC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRC_L,0))*ISNULL(QTE_ARTICLE_BRC_L,0)
END)
*ISNULL(FODEC_BRC_L,0)/100
as TOTAL_ARTICLE_FODEC_BRC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0)
-
CASE WHEN TYPE_REMISE_BRC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_BRC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRC_L,0))*ISNULL(QTE_ARTICLE_BRC_L,0)
END)
*ISNULL(TPE_BRC_L,0)/100
as TOTAL_ARTICLE_TPE_BRC_L,
ISNULL(TAXE_ENERGIE_BRC_L,0)*ISNULL(QTE_ARTICLE_BRC_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_BRC_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_BRC_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_BRC_L
WHEN TYPE_DROIT_CONSOMMATION_BRC_L='% PRIX' THEN PRIX_VENTE_ARTICLE_HT_NET_BRC_L*VALEUR_DROIT_CONSOMMATION_BRC_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_BRC_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_BRC_L,
TAUX_ARTICLE_TVA_BRC_L,
QTE_ARTICLE_BRC_L,
NOMBRE_CARTON_BRC_L,
POIDS_ARTICLE_BRUT_BRC_L,
POIDS_ARTICLE_NET_BRC_L

from BON_RETOUR_CLIENT_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_BRC_L+TOTAL_ARTICLE_FODEC_BRC_L+TOTAL_ARTICLE_TPE_BRC_L+TOTAL_ARTICLE_TAXE_ENERGIE_BRC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BRC_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_BRC_L,
(TOTAL_ARTICLE_HT_BRUT_BRC_L+TOTAL_ARTICLE_FODEC_BRC_L+TOTAL_ARTICLE_TPE_BRC_L+TOTAL_ARTICLE_TAXE_ENERGIE_BRC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BRC_L )*ISNULL(TAUX_ARTICLE_TVA_BRC_L,0)/100 
as TOTAL_ARTICLE_TVA_BRC_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_BRC_L+TOTAL_ARTICLE_TVA_BRC_L as TOTAL_ARTICLE_TTC_BRC_L
from CTE1

GO

-----------------------------------------------------------------------------------------

create view VUE_AVOIR_CLIENT_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_AC_L,
AC_ID,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0) 
as TOTAL_ARTICLE_HT_BRUT_AC_L,
CASE WHEN TYPE_REMISE_AC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AC_L,0))*ISNULL(QTE_ARTICLE_AC_L,0)
END	
as TOTAL_ARTICLE_REMISE_AC_L,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0)
-
CASE WHEN TYPE_REMISE_AC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AC_L,0))*ISNULL(QTE_ARTICLE_AC_L,0)
END
as TOTAL_ARTICLE_HT_NET_AC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0)
-
CASE WHEN TYPE_REMISE_AC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AC_L,0))*ISNULL(QTE_ARTICLE_AC_L,0)
END)
*ISNULL(FODEC_AC_L,0)/100
as TOTAL_ARTICLE_FODEC_AC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0)
-
CASE WHEN TYPE_REMISE_AC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_AC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AC_L,0))*ISNULL(QTE_ARTICLE_AC_L,0)
END)
*ISNULL(TPE_AC_L,0)/100
as TOTAL_ARTICLE_TPE_AC_L,
ISNULL(TAXE_ENERGIE_AC_L,0)*ISNULL(QTE_ARTICLE_AC_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_AC_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_AC_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_AC_L
WHEN TYPE_DROIT_CONSOMMATION_AC_L='% PRIX' THEN PRIX_VENTE_ARTICLE_HT_NET_AC_L*VALEUR_DROIT_CONSOMMATION_AC_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_AC_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_AC_L,
TAUX_ARTICLE_TVA_AC_L,
QTE_ARTICLE_AC_L,
NOMBRE_CARTON_AC_L,
POIDS_ARTICLE_BRUT_AC_L,
POIDS_ARTICLE_NET_AC_L

from AVOIR_CLIENT_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_AC_L+TOTAL_ARTICLE_FODEC_AC_L+TOTAL_ARTICLE_TPE_AC_L+TOTAL_ARTICLE_TAXE_ENERGIE_AC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_AC_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_AC_L,
(TOTAL_ARTICLE_HT_BRUT_AC_L+TOTAL_ARTICLE_FODEC_AC_L+TOTAL_ARTICLE_TPE_AC_L+TOTAL_ARTICLE_TAXE_ENERGIE_AC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_AC_L )*ISNULL(TAUX_ARTICLE_TVA_AC_L,0)/100 
as TOTAL_ARTICLE_TVA_AC_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_AC_L+TOTAL_ARTICLE_TVA_AC_L as TOTAL_ARTICLE_TTC_AC_L
from CTE1

GO

----------------------------------------------------------------------------------


create view VUE_DEVIS_CLIENT_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_DC_L,
DC_ID,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0) 
as TOTAL_ARTICLE_HT_BRUT_DC_L,
CASE WHEN TYPE_REMISE_DC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_DC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_DC_L,0))*ISNULL(QTE_ARTICLE_DC_L,0)
END	
as TOTAL_ARTICLE_REMISE_DC_L,
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0)
-
CASE WHEN TYPE_REMISE_DC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_DC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_DC_L,0))*ISNULL(QTE_ARTICLE_DC_L,0)
END
as TOTAL_ARTICLE_HT_NET_DC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0)
-
CASE WHEN TYPE_REMISE_DC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_DC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_DC_L,0))*ISNULL(QTE_ARTICLE_DC_L,0)
END)
*ISNULL(FODEC_DC_L,0)/100
as TOTAL_ARTICLE_FODEC_DC_L,
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0)
-
CASE WHEN TYPE_REMISE_DC_L='P' 
THEN 
ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0)*ISNULL(TAUX_REMISE_ARTICLE_DC_L,0)/100 
ELSE 
(ISNULL(PRIX_VENTE_ARTICLE_HT_BRUT_DC_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_DC_L,0))*ISNULL(QTE_ARTICLE_DC_L,0)
END)
*ISNULL(TPE_DC_L,0)/100
as TOTAL_ARTICLE_TPE_DC_L,
ISNULL(TAXE_ENERGIE_DC_L,0)*ISNULL(QTE_ARTICLE_DC_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_DC_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_DC_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_DC_L
WHEN TYPE_DROIT_CONSOMMATION_DC_L='% PRIX' THEN PRIX_VENTE_ARTICLE_HT_NET_DC_L*VALEUR_DROIT_CONSOMMATION_DC_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_DC_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_DC_L,
TAUX_ARTICLE_TVA_DC_L,
QTE_ARTICLE_DC_L,
NOMBRE_CARTON_DC_L,
POIDS_ARTICLE_BRUT_DC_L,
POIDS_ARTICLE_NET_DC_L

from DEVIS_CLIENT_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_DC_L+TOTAL_ARTICLE_FODEC_DC_L+TOTAL_ARTICLE_TPE_DC_L+TOTAL_ARTICLE_TAXE_ENERGIE_DC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_DC_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_DC_L,
(TOTAL_ARTICLE_HT_BRUT_DC_L+TOTAL_ARTICLE_FODEC_DC_L+TOTAL_ARTICLE_TPE_DC_L+TOTAL_ARTICLE_TAXE_ENERGIE_DC_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_DC_L )*ISNULL(TAUX_ARTICLE_TVA_DC_L,0)/100 
as TOTAL_ARTICLE_TVA_DC_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_DC_L+TOTAL_ARTICLE_TVA_DC_L as TOTAL_ARTICLE_TTC_DC_L
from CTE1

GO

------------------------------------------------------------------------------

create view VUE_BON_COMMANDE_FOURNISSEUR_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_BCF_L,
BCF_ID,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0) 
as TOTAL_ARTICLE_HT_BRUT_BCF_L,
CASE WHEN TYPE_REMISE_BCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCF_L,0))*ISNULL(QTE_ARTICLE_BCF_L,0)
END	
as TOTAL_ARTICLE_REMISE_BCF_L,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0)
-
CASE WHEN TYPE_REMISE_BCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCF_L,0))*ISNULL(QTE_ARTICLE_BCF_L,0)
END
as TOTAL_ARTICLE_HT_NET_BCF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0)
-
CASE WHEN TYPE_REMISE_BCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCF_L,0))*ISNULL(QTE_ARTICLE_BCF_L,0)
END)
*ISNULL(FODEC_BCF_L,0)/100
as TOTAL_ARTICLE_FODEC_BCF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0)
-
CASE WHEN TYPE_REMISE_BCF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BCF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BCF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BCF_L,0))*ISNULL(QTE_ARTICLE_BCF_L,0)
END)
*ISNULL(TPE_BCF_L,0)/100
as TOTAL_ARTICLE_TPE_BCF_L,
ISNULL(TAXE_ENERGIE_BCF_L,0)*ISNULL(QTE_ARTICLE_BCF_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_BCF_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_BCF_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_BCF_L
WHEN TYPE_DROIT_CONSOMMATION_BCF_L='% PRIX' THEN PRIX_ACHAT_ARTICLE_HT_NET_BCF_L*VALEUR_DROIT_CONSOMMATION_BCF_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_BCF_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_BCF_L,
TAUX_ARTICLE_TVA_BCF_L,
QTE_ARTICLE_BCF_L,
NOMBRE_CARTON_BCF_L,
POIDS_ARTICLE_BRUT_BCF_L,
POIDS_ARTICLE_NET_BCF_L

from BON_COMMANDE_FOURNISSEUR_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_BCF_L+TOTAL_ARTICLE_FODEC_BCF_L+TOTAL_ARTICLE_TPE_BCF_L+TOTAL_ARTICLE_TAXE_ENERGIE_BCF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BCF_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_BCF_L,
(TOTAL_ARTICLE_HT_BRUT_BCF_L+TOTAL_ARTICLE_FODEC_BCF_L+TOTAL_ARTICLE_TPE_BCF_L+TOTAL_ARTICLE_TAXE_ENERGIE_BCF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BCF_L )*ISNULL(TAUX_ARTICLE_TVA_BCF_L,0)/100 
as TOTAL_ARTICLE_TVA_BCF_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_BCF_L+TOTAL_ARTICLE_TVA_BCF_L as TOTAL_ARTICLE_TTC_BCF_L
from CTE1

GO
--------------------------------------------------------------------------------------

create view VUE_BON_RETOUR_FOURNISSEUR_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_BTF_L,
BTF_ID,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0) 
as TOTAL_ARTICLE_HT_BRUT_BTF_L,
CASE WHEN TYPE_REMISE_BTF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BTF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BTF_L,0))*ISNULL(QTE_ARTICLE_BTF_L,0)
END	
as TOTAL_ARTICLE_REMISE_BTF_L,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0)
-
CASE WHEN TYPE_REMISE_BTF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BTF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BTF_L,0))*ISNULL(QTE_ARTICLE_BTF_L,0)
END
as TOTAL_ARTICLE_HT_NET_BTF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0)
-
CASE WHEN TYPE_REMISE_BTF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BTF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BTF_L,0))*ISNULL(QTE_ARTICLE_BTF_L,0)
END)
*ISNULL(FODEC_BTF_L,0)/100
as TOTAL_ARTICLE_FODEC_BTF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0)
-
CASE WHEN TYPE_REMISE_BTF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BTF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BTF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BTF_L,0))*ISNULL(QTE_ARTICLE_BTF_L,0)
END)
*ISNULL(TPE_BTF_L,0)/100
as TOTAL_ARTICLE_TPE_BTF_L,
ISNULL(TAXE_ENERGIE_BTF_L,0)*ISNULL(QTE_ARTICLE_BTF_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_BTF_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_BTF_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_BTF_L
WHEN TYPE_DROIT_CONSOMMATION_BTF_L='% PRIX' THEN PRIX_ACHAT_ARTICLE_HT_NET_BTF_L*VALEUR_DROIT_CONSOMMATION_BTF_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_BTF_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_BTF_L,
TAUX_ARTICLE_TVA_BTF_L,
QTE_ARTICLE_BTF_L,
NOMBRE_CARTON_BTF_L,
POIDS_ARTICLE_BRUT_BTF_L,
POIDS_ARTICLE_NET_BTF_L

from BON_RETOUR_FOURNISSEUR_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_BTF_L+TOTAL_ARTICLE_FODEC_BTF_L+TOTAL_ARTICLE_TPE_BTF_L+TOTAL_ARTICLE_TAXE_ENERGIE_BTF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BTF_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_BTF_L,
(TOTAL_ARTICLE_HT_BRUT_BTF_L+TOTAL_ARTICLE_FODEC_BTF_L+TOTAL_ARTICLE_TPE_BTF_L+TOTAL_ARTICLE_TAXE_ENERGIE_BTF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BTF_L )*ISNULL(TAUX_ARTICLE_TVA_BTF_L,0)/100 
as TOTAL_ARTICLE_TVA_BTF_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_BTF_L+TOTAL_ARTICLE_TVA_BTF_L as TOTAL_ARTICLE_TTC_BTF_L
from CTE1

GO

------------------------------------------------------------------------

create view VUE_AVOIR_FOURNISSEUR_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_AF_L,
AF_ID,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0) 
as TOTAL_ARTICLE_HT_BRUT_AF_L,
CASE WHEN TYPE_REMISE_AF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AF_L,0))*ISNULL(QTE_ARTICLE_AF_L,0)
END	
as TOTAL_ARTICLE_REMISE_AF_L,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0)
-
CASE WHEN TYPE_REMISE_AF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AF_L,0))*ISNULL(QTE_ARTICLE_AF_L,0)
END
as TOTAL_ARTICLE_HT_NET_AF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0)
-
CASE WHEN TYPE_REMISE_AF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AF_L,0))*ISNULL(QTE_ARTICLE_AF_L,0)
END)
*ISNULL(FODEC_AF_L,0)/100
as TOTAL_ARTICLE_FODEC_AF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0)
-
CASE WHEN TYPE_REMISE_AF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_AF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_AF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_AF_L,0))*ISNULL(QTE_ARTICLE_AF_L,0)
END)
*ISNULL(TPE_AF_L,0)/100
as TOTAL_ARTICLE_TPE_AF_L,
ISNULL(TAXE_ENERGIE_AF_L,0)*ISNULL(QTE_ARTICLE_AF_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_AF_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_AF_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_AF_L
WHEN TYPE_DROIT_CONSOMMATION_AF_L='% PRIX' THEN PRIX_ACHAT_ARTICLE_HT_NET_AF_L*VALEUR_DROIT_CONSOMMATION_AF_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_AF_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_AF_L,
TAUX_ARTICLE_TVA_AF_L,
QTE_ARTICLE_AF_L,
NOMBRE_CARTON_AF_L,
POIDS_ARTICLE_BRUT_AF_L,
POIDS_ARTICLE_NET_AF_L

from AVOIR_FOURNISSEUR_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_AF_L+TOTAL_ARTICLE_FODEC_AF_L+TOTAL_ARTICLE_TPE_AF_L+TOTAL_ARTICLE_TAXE_ENERGIE_AF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_AF_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_AF_L,
(TOTAL_ARTICLE_HT_BRUT_AF_L+TOTAL_ARTICLE_FODEC_AF_L+TOTAL_ARTICLE_TPE_AF_L+TOTAL_ARTICLE_TAXE_ENERGIE_AF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_AF_L )*ISNULL(TAUX_ARTICLE_TVA_AF_L,0)/100 
as TOTAL_ARTICLE_TVA_AF_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_AF_L+TOTAL_ARTICLE_TVA_AF_L as TOTAL_ARTICLE_TTC_AF_L
from CTE1

GO

------------------------------------------------------------------------------


create view VUE_BON_RECEPTION_FOURNISSEUR_LIGNE_ARRONDISSEMENT
as

with CTE as (
select 
ID_BRF_L,
BRF_ID,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0) 
as TOTAL_ARTICLE_HT_BRUT_BRF_L,
CASE WHEN TYPE_REMISE_BRF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRF_L,0))*ISNULL(QTE_ARTICLE_BRF_L,0)
END	
as TOTAL_ARTICLE_REMISE_BRF_L,
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0)
-
CASE WHEN TYPE_REMISE_BRF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRF_L,0))*ISNULL(QTE_ARTICLE_BRF_L,0)
END
as TOTAL_ARTICLE_HT_NET_BRF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0)
-
CASE WHEN TYPE_REMISE_BRF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRF_L,0))*ISNULL(QTE_ARTICLE_BRF_L,0)
END)
*ISNULL(FODEC_BRF_L,0)/100
as TOTAL_ARTICLE_FODEC_BRF_L,
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0)
-
CASE WHEN TYPE_REMISE_BRF_L='P' 
THEN 
ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0)*ISNULL(TAUX_REMISE_ARTICLE_BRF_L,0)/100 
ELSE 
(ISNULL(PRIX_ACHAT_ARTICLE_HT_BRUT_BRF_L,0)-ISNULL(MONTANT_REMISE_ARTICLE_BRF_L,0))*ISNULL(QTE_ARTICLE_BRF_L,0)
END)
*ISNULL(TPE_BRF_L,0)/100
as TOTAL_ARTICLE_TPE_BRF_L,
ISNULL(TAXE_ENERGIE_BRF_L,0)*ISNULL(QTE_ARTICLE_BRF_L,0) 
as TOTAL_ARTICLE_TAXE_ENERGIE_BRF_L,
ISNULL(CASE 
WHEN TYPE_DROIT_CONSOMMATION_BRF_L='UNITE' THEN VALEUR_DROIT_CONSOMMATION_BRF_L
WHEN TYPE_DROIT_CONSOMMATION_BRF_L='% PRIX' THEN PRIX_ACHAT_ARTICLE_HT_NET_BRF_L*VALEUR_DROIT_CONSOMMATION_BRF_L/100  ELSE NULL END,0)
*
ISNULL(QTE_ARTICLE_BRF_L,0)
as TOTAL_ARTICLE_DROIT_CONSOMMATION_BRF_L,
TAUX_ARTICLE_TVA_BRF_L,
QTE_ARTICLE_BRF_L,
NOMBRE_CARTON_BRF_L,
POIDS_ARTICLE_BRUT_BRF_L,
POIDS_ARTICLE_NET_BRF_L

from BON_RECEPTION_FOURNISSEUR_LIGNE

)
,CTE1 as (
select 
*,
TOTAL_ARTICLE_HT_BRUT_BRF_L+TOTAL_ARTICLE_FODEC_BRF_L+TOTAL_ARTICLE_TPE_BRF_L+TOTAL_ARTICLE_TAXE_ENERGIE_BRF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BRF_L 
as TOTAL_ARTICLE_ASSIETTE_TVA_BRF_L,
(TOTAL_ARTICLE_HT_BRUT_BRF_L+TOTAL_ARTICLE_FODEC_BRF_L+TOTAL_ARTICLE_TPE_BRF_L+TOTAL_ARTICLE_TAXE_ENERGIE_BRF_L+TOTAL_ARTICLE_DROIT_CONSOMMATION_BRF_L )*ISNULL(TAUX_ARTICLE_TVA_BRF_L,0)/100 
as TOTAL_ARTICLE_TVA_BRF_L
from CTE
)
select 
*,
TOTAL_ARTICLE_ASSIETTE_TVA_BRF_L+TOTAL_ARTICLE_TVA_BRF_L as TOTAL_ARTICLE_TTC_BRF_L
from CTE1

GO

-------------------------------------------------------------

ALTER VIEW [dbo].[VUE_SOCIETE]
AS
SELECT        dbo.SOCIETE.ID_SOCIETE, dbo.SOCIETE.ID_SOCIETE AS SOCIETE_ID, dbo.SOCIETE.ABONNE_ID, dbo.SOCIETE.NOM_SOCIETE, dbo.SOCIETE.ADRESSE_LIGNE1_SOCIETE, dbo.SOCIETE.ADRESSE_LIGNE2_SOCIETE, 
                         dbo.SOCIETE.VILLE_SOCIETE, dbo.SOCIETE.PAYS_SOCIETE_ID, dbo.SOCIETE.TELEPHONE_SOCIETE, dbo.SOCIETE.FAX_SOCIETE, dbo.SOCIETE.EMAIL_SOCIETE, dbo.SOCIETE.SITE_WEB_SOCIETE, 
                         dbo.SOCIETE.MATRICULE_FISCAL_SOCIETE, dbo.SOCIETE.REGISTRE_COMMERCE_SOCIETE, dbo.SOCIETE.RIB_SOCIETE, dbo.SOCIETE.BANQUE_SOCIETE, dbo.SOCIETE.LOGO_SOCIETE, dbo.SOCIETE.DEVISE_SOCIETE_ID, 
                         dbo.SOCIETE.DEPOT_SOCIETE_ID, dbo.SOCIETE.GESTION_STOCK, dbo.SOCIETE.STOCK_ZERO_NEGATIF, dbo.SOCIETE.USER_CREATION_ID, dbo.SOCIETE.DATE_CREATION, dbo.SOCIETE.USER_MODIF_ID, 
                         dbo.SOCIETE.DATE_MODIF, dbo.DEVISE_BASE.NOM_DEVISE, dbo.PAYS.NOM_PAYS, dbo.DEPOT.NOM_DEPOT, dbo.DEVISE_BASE.NOMBRE_DECIMAL, dbo.SOCIETE.TIMBRE_SOCIETE, dbo.DEVISE_BASE.LIBELLE_DEVISE, 
                         dbo.SOCIETE.VISIBILITE_MENU_SOCIETE, dbo.SOCIETE.FODEC_ACHAT_SOCIETE, dbo.SOCIETE.FODEC_VENTE_SOCIETE, dbo.SOCIETE.TVA_SOCIETE_ID, dbo.SOCIETE.MAJ_PRIX_ACHAT_SOCIETE, 
                         dbo.SOCIETE.MAJ_MARGE_SOCIETE, dbo.SOCIETE.MARGE_SOCIETE, dbo.SOCIETE.CLIENT_SOCIETE_ID, dbo.TVA_ARTICLE.TAUX_TVA_ARTICLE, dbo.SOCIETE.TYPE_CALCUL_SOCIETE, dbo.CLIENT.NOM_CLIENT, 
                         dbo.SOCIETE.CLIENT_ETATIQUE_SOCIETE, dbo.SOCIETE.FOURNISSEUR_SOCIETE_ID, dbo.FOURNISSEUR.NOM_FOURNISSEUR, dbo.FOURNISSEUR.NUMERO_FOURNISSEUR, dbo.CLIENT.NUMERO_CLIENT, 
                         dbo.SOCIETE.MAJ_PRIX_VENTE_SOCIETE, dbo.SOCIETE.MODELE_IMPRESSION_DC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BCC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BLC_SOCIETE_ID, 
                         dbo.SOCIETE.MODELE_IMPRESSION_FCC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BRC_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_AC_SOCIETE_ID, 
                         dbo.SOCIETE.MODELE_IMPRESSION_BCF_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_BRF_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_FCF_SOCIETE_ID, 
                         dbo.SOCIETE.MODELE_IMPRESSION_BTF_SOCIETE_ID, dbo.SOCIETE.MODELE_IMPRESSION_AF_SOCIETE_ID, M1.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_DC, 
                         M2.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BCC, M3.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BLC, M4.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_FCC, 
                         M5.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BRC, M6.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_AC, M7.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BCF, 
                         M8.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BRF, M9.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_FCF, M10.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_BTF, 
                         M11.NOM_MODELE_IMPRESSION AS NOM_MODELE_IMPRESSION_AF, dbo.SOCIETE.QUANTITE_ARTICLE_SOCIETE, dbo.SOCIETE.PRIX_ACHAT_SOCIETE, dbo.SOCIETE.RETENUE_SOURCE_SOCIETE_ID, 
                         dbo.SOCIETE.SIGNATURE_DC_SOCIETE, dbo.SOCIETE.SIGNATURE_BCC_SOCIETE, dbo.SOCIETE.SIGNATURE_BLC_SOCIETE, dbo.SOCIETE.SIGNATURE_FCC_SOCIETE, dbo.SOCIETE.SIGNATURE_BRC_SOCIETE, 
                         dbo.SOCIETE.SIGNATURE_AC_SOCIETE, dbo.SOCIETE.SIGNATURE_SOCIETE, dbo.SOCIETE.CHOIX_MODELE_IMPRESSION_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_DC_SOCIETE, 
                         dbo.SOCIETE.CONDITION_IMPRESSION_BCC_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_BLC_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_FCC_SOCIETE, dbo.SOCIETE.CONDITION_IMPRESSION_BRC_SOCIETE, 
                         dbo.SOCIETE.CONDITION_IMPRESSION_AC_SOCIETE, dbo.RETENUE_SOURCE.POURCENTAGE_RS, dbo.SOCIETE.UNITE_ARTICLE_SOCIETE_ID, dbo.SOCIETE.FAMILLE_ARTICLE_SOCIETE_ID, 
                         dbo.SOCIETE.MARQUE_ARTICLE_SOCIETE_ID, dbo.SOCIETE.CATEGORIE_ARTICLE_SOCIETE_ID, dbo.UNITE_ARTICLE.NOM_UNITE_ARTICLE, dbo.FAMILLE_ARTICLE.NOM_FAMILLE_ARTICLE, 
                         dbo.MARQUE_ARTICLE.NOM_MARQUE_ARTICLE, dbo.CATEGORIE_ARTICLE.NOM_CATEGORIE_ARTICLE, dbo.SOCIETE.GARANTIE_MOIS_ARTICLE_SOCIETE, dbo.SOCIETE.TPE_ACHAT_SOCIETE, 
                         dbo.SOCIETE.TPE_VENTE_SOCIETE, dbo.SOCIETE.CLIENT_CAISSE_SOCIETE_ID, dbo.SOCIETE.ENTETE_DOCUMENT_DC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_DC_SOCIETE, 
                         dbo.SOCIETE.ENTETE_DOCUMENT_BCC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_BCC_SOCIETE, dbo.SOCIETE.ENTETE_DOCUMENT_BLC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_BLC_SOCIETE, 
                         dbo.SOCIETE.ENTETE_DOCUMENT_FCC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_FCC_SOCIETE, dbo.SOCIETE.ENTETE_DOCUMENT_BRC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_BRC_SOCIETE, 
                         dbo.SOCIETE.ENTETE_DOCUMENT_AC_SOCIETE, dbo.SOCIETE.PIED_PAGE_DOCUMENT_AC_SOCIETE, dbo.SOCIETE.TYPE_TRANSFERT_CAISSE_SOCIETE, dbo.SOCIETE.NBR_JOUR_ARCHIVE_TICKET_CAISSE_SOCIETE, 
                         C.NOM_CLIENT AS NOM_CLIENT_CAISSE, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_DC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BCC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BLC, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_FCC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_AC, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_DF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BCF, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BRF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_FCF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_AF, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BRC, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_ES, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_SS, dbo.SOCIETE.IMPRESSION_DOCUMENT_ZERO_BTF, dbo.SOCIETE.FACTURE_CLIENT_STOCK, 
                         dbo.SOCIETE.FACTURE_FOURNISSEUR_STOCK, dbo.SOCIETE.AVOIR_FOURNISSEUR_STOCK, dbo.SOCIETE.AVOIR_CLIENT_STOCK, dbo.SOCIETE.REINITIALISER_PARAM_CAISSE_SOCIETE, 
                         dbo.SOCIETE.IMPRESSION_DOCUMENT_SOURCE, dbo.SOCIETE.CODE_BARRE_NUM_AUTO_SOCIETE, dbo.SOCIETE.CODE_BARRE_INIT_AUTO_SOCIETE, dbo.SOCIETE.NUMERO_SERIE_OBLIGATOIRE_SOCIETE, 
                         dbo.SOCIETE.DESCRIPTION_SOCIETE, dbo.SOCIETE.GSM_SOCIETE, dbo.SOCIETE.DESCRIPTION_NOTE_HONORAIRE_SOCIETE, dbo.SOCIETE.NUMERO_SERIE_UNIQUE_SOCIETE, 
                         dbo.SOCIETE.TYPE_CALCUL_ARRONDISSEMENT_SOCIETE
FROM            dbo.SOCIETE INNER JOIN
                         dbo.DEPOT ON dbo.SOCIETE.DEPOT_SOCIETE_ID = dbo.DEPOT.ID_DEPOT AND dbo.SOCIETE.ID_SOCIETE = dbo.DEPOT.SOCIETE_ID INNER JOIN
                         dbo.DEVISE ON dbo.SOCIETE.DEVISE_SOCIETE_ID = dbo.DEVISE.ID_DEVISE AND dbo.SOCIETE.ID_SOCIETE = dbo.DEVISE.SOCIETE_ID INNER JOIN
                         dbo.DEVISE_BASE ON dbo.DEVISE.DEVISE_DEVISE_ID = dbo.DEVISE_BASE.ID_DEVISE_BASE LEFT OUTER JOIN
                         dbo.PAYS ON dbo.SOCIETE.PAYS_SOCIETE_ID = dbo.PAYS.ID_PAYS LEFT OUTER JOIN
                         dbo.TVA_ARTICLE ON dbo.TVA_ARTICLE.ID_TVA_ARTICLE = dbo.SOCIETE.TVA_SOCIETE_ID LEFT OUTER JOIN
                         dbo.CLIENT ON dbo.CLIENT.ID_CLIENT = dbo.SOCIETE.CLIENT_SOCIETE_ID LEFT OUTER JOIN
                         dbo.FOURNISSEUR ON dbo.FOURNISSEUR.ID_FOURNISSEUR = dbo.SOCIETE.FOURNISSEUR_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M1 ON M1.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_DC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M2 ON M2.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BCC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M3 ON M3.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BLC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M4 ON M4.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_FCC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M5 ON M5.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BRC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M6 ON M6.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_AC_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M7 ON M7.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BCF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M8 ON M8.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BRF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M9 ON M9.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_FCF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M10 ON M10.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_BTF_SOCIETE_ID INNER JOIN
                         dbo.MODELE_IMPRESSION AS M11 ON M11.ID_MODELE_IMPRESSION = dbo.SOCIETE.MODELE_IMPRESSION_AF_SOCIETE_ID LEFT OUTER JOIN
                         dbo.RETENUE_SOURCE ON dbo.RETENUE_SOURCE.ID_RS = dbo.SOCIETE.RETENUE_SOURCE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.UNITE_ARTICLE ON dbo.UNITE_ARTICLE.ID_UNITE_ARTICLE = dbo.SOCIETE.UNITE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.FAMILLE_ARTICLE ON dbo.FAMILLE_ARTICLE.ID_FAMILLE_ARTICLE = dbo.SOCIETE.FAMILLE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.MARQUE_ARTICLE ON dbo.MARQUE_ARTICLE.ID_MARQUE_ARTICLE = dbo.SOCIETE.MARQUE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.CATEGORIE_ARTICLE ON dbo.CATEGORIE_ARTICLE.ID_CATEGORIE_ARTICLE = dbo.SOCIETE.CATEGORIE_ARTICLE_SOCIETE_ID LEFT OUTER JOIN
                         dbo.CLIENT AS C ON C.ID_CLIENT = dbo.SOCIETE.CLIENT_CAISSE_SOCIETE_ID
GO


-------------------------------------------------------------------------------

insert CONTROLE  (ID_CTRL,PAGE_ID,ID_DESIGN_CTRL,VALEUR_DEFAUT_CTRL,LISTE_DDL,VALEUR_VIDE_CTRL,CHAMPS_CALCULE_CTRL,MODIFIABLE_INSERT_CTRL,MODIFIABLE_UPDATE_CTRL,CHAMPS_CACHE_CTRL,MONNAIE_CTRL,TRONQUER_ZERO_CTRL,CHAMPS_CTRL) values (993,'65','C112','''PAR LIGNE''','select ''PAR LIGNE'',''TOTAL''','''PAR LIGNE''','0','1','1','0','0','0','TYPE_CALCUL_ARRONDISSEMENT_SOCIETE')




