
IF OBJECT_ID('VUE_ARTICLE_DEVISE_PROPRIETE', 'V') IS NOT NULL  
    DROP VIEW VUE_ARTICLE_DEVISE_PROPRIETE;  
GO

CREATE VIEW [dbo].[VUE_ARTICLE_DEVISE_PROPRIETE]
as
SELECT        
ROW_NUMBER() over(order by A.ID_ARTICLE) as ROW_INDEX,A.ID_ARTICLE, A.CODE_ARTICLE, A.LIBELLE_ARTICLE, A.UNITE_ARTICLE_ID, U.NOM_UNITE_ARTICLE, D.PRIX_ACHAT_ARTICLE_HT_ARTICLE_L AS PRIX_ACHAT_ARTICLE_HT, NULL AS TVA_ARTICLE_ID, NULL 
AS TVA_ARTICLE_TVA, D.PRIX_VENTE_ARTICLE_HT_ARTICLE_L AS PRIX_VENTE_ARTICLE_HT, CASE WHEN ARTICLE_PROPRIETE.TAILLE_ID is not NULL or ARTICLE_PROPRIETE.COULEUR_ID is not NULL THEN ISNULL(STOCK_PROPRIETE.QUANTITE_STOCK_PROPRIETE,0) ELSE A.QUANTITE_STOCK END as QUANTITE_STOCK, A.BLOQUE_ARTICLE, A.SOCIETE_ID, dbo.TVA_ARTICLE.TAUX_TVA_ARTICLE, V.ID_DEVISE, 
A.DEPOT_ARTICLE_ID, dbo.DEPOT.NOM_DEPOT, A.FODEC_ACHAT_ARTICLE, A.FODEC_VENTE_ARTICLE, A.QUANTITE_ARTICLE, CAST(0 AS bit) AS SELECTION_ARTICLE, A.POIDS_NET_KG, A.POIDS_BRUT_KG, 
A.TPE_ACHAT_ARTICLE, A.TPE_VENTE_ARTICLE, A.TYPE_DROIT_CONSOMMATION_ARTICLE, A.VALEUR_DROIT_CONSOMMATION_ARTICLE, A.DROIT_CONSOMMATION_ACHAT_ARTICLE, 
A.DROIT_CONSOMMATION_VENTE_ARTICLE,						 
TAILLE.NOM_TAILLE,COULEUR.NOM_COULEUR
FROM dbo.ARTICLE AS A 
LEFT JOIN ARTICLE_PROPRIETE on ARTICLE_PROPRIETE.ARTICLE_ID=A.ID_ARTICLE
left JOIN TAILLE on TAILLE.ID_TAILLE=ARTICLE_PROPRIETE.TAILLE_ID 
left JOIN COULEUR on COULEUR.ID_COULEUR=ARTICLE_PROPRIETE.COULEUR_ID
LEFT JOIN STOCK_PROPRIETE on STOCK_PROPRIETE.ARTICLE_PROPRIETE_ID=A.ID_ARTICLE
and STOCK_PROPRIETE.TAILLE_PROPRIETE_ID=TAILLE.ID_TAILLE and STOCK_PROPRIETE.COULEUR_PROPRIETE_ID=COULEUR.ID_COULEUR
INNER JOIN dbo.DEVISE AS V ON V.SOCIETE_ID=A.SOCIETE_ID 
INNER JOIN dbo.DEPOT ON A.DEPOT_ARTICLE_ID = dbo.DEPOT.ID_DEPOT 
LEFT OUTER JOIN dbo.TVA_ARTICLE ON A.TVA_ARTICLE_ID = dbo.TVA_ARTICLE.ID_TVA_ARTICLE 
LEFT JOIN dbo.ARTICLE_DEVISE AS D ON A.ID_ARTICLE = D.ARTICLE_ID 
LEFT OUTER JOIN dbo.UNITE_ARTICLE AS U ON U.ID_UNITE_ARTICLE = A.UNITE_ARTICLE_ID
GO


--------------------------------------------------------------------------------------

update GRID set TABLE_GRID='VUE_ARTICLE_DEVISE_PROPRIETE',TABLE_GRID_UPDATE='VUE_ARTICLE_DEVISE_PROPRIETE'
where ID_GRID=37
GO

-------------------------------------
IF OBJECT_ID('VUE_ARTICLE_PROPRIETE', 'V') IS NOT NULL  
    DROP VIEW VUE_ARTICLE_PROPRIETE;  
GO

CREATE VIEW [dbo].[VUE_ARTICLE_PROPRIETE]
AS
SELECT dbo.ARTICLE.ID_ARTICLE, dbo.ARTICLE.SOCIETE_ID, dbo.ARTICLE.CODE_ARTICLE, dbo.ARTICLE.LIBELLE_ARTICLE, dbo.ARTICLE.LIBELLE_ARTICLE_LANGUE_2, dbo.ARTICLE.DEPOT_ARTICLE_ID, 
dbo.ARTICLE.FAMILLE_ARTICLE_ID, dbo.ARTICLE.TVA_ARTICLE_ID, dbo.ARTICLE.PRIX_ACHAT_ARTICLE_HT, dbo.ARTICLE.PRIX_ACHAT_ARTICLE_TTC, dbo.ARTICLE.MARGE_ARTICLE, ARTICLE.PRIX_VENTE_ARTICLE_HT as PRIX_VENTE_ARTICLE_HT, 
dbo.ARTICLE.PRIX_VENTE_ARTICLE_TTC as PRIX_VENTE_ARTICLE_TTC, dbo.ARTICLE.GESTION_STOCK, CASE WHEN ARTICLE_PROPRIETE.TAILLE_ID is not NULL or ARTICLE_PROPRIETE.COULEUR_ID is not NULL THEN ISNULL(STOCK_PROPRIETE.QUANTITE_STOCK_PROPRIETE,0) ELSE ARTICLE.QUANTITE_STOCK END as QUANTITE_STOCK, dbo.ARTICLE.PAMP_ARTICLE, dbo.ARTICLE.QUANTITE_STOCK_MIN, dbo.ARTICLE.QUANTITE_STOCK_MAX, 
dbo.ARTICLE.CODE_BARRE_ARTICLE, dbo.ARTICLE.MARQUE_ARTICLE_ID, dbo.ARTICLE.CATEGORIE_ARTICLE_ID, dbo.ARTICLE.UNITE_ARTICLE_ID, dbo.UNITE_ARTICLE.NOM_UNITE_ARTICLE, dbo.ARTICLE.GARANTIE_MOIS, 
dbo.ARTICLE.POIDS_NET_KG, dbo.ARTICLE.POIDS_BRUT_KG, dbo.ARTICLE.BLOQUE_ARTICLE, dbo.ARTICLE.IMAGE_ARTICLE, dbo.ARTICLE.OBSERVATION, dbo.ARTICLE.USER_CREATION_ID, dbo.ARTICLE.DATE_CREATION, 
dbo.ARTICLE.USER_MODIF_ID, dbo.ARTICLE.DATE_MODIF, dbo.FAMILLE_ARTICLE.NOM_FAMILLE_ARTICLE, dbo.TVA_ARTICLE.TAUX_TVA_ARTICLE, dbo.MARQUE_ARTICLE.NOM_MARQUE_ARTICLE, 
dbo.CATEGORIE_ARTICLE.NOM_CATEGORIE_ARTICLE, dbo.DEPOT.NOM_DEPOT, dbo.ARTICLE.TYPE_CALCUL, dbo.ARTICLE.DIVERS_ARTICLE, dbo.ARTICLE.FODEC_ACHAT_ARTICLE, dbo.ARTICLE.FODEC_VENTE_ARTICLE, 
dbo.ARTICLE.QUANTITE_ARTICLE, dbo.ARTICLE.TPE_ACHAT_ARTICLE, dbo.ARTICLE.TPE_VENTE_ARTICLE, dbo.ARTICLE.BALANCE_ARTICLE, dbo.ARTICLE.PRIX_VENTE_PUBLIC_ARTICLE, 
dbo.ARTICLE.NUMERO_SERIE_OBLIGATOIRE_ARTICLE, CAST(0 AS bit) AS SELECTION_ARTICLE, dbo.ARTICLE.CHARGE_ARTICLE, ISNULL(dbo.ARTICLE.PRIX_ACHAT_ARTICLE_HT, 0) + ISNULL(dbo.ARTICLE.CHARGE_ARTICLE, 
0) AS PRIX_REVIENT_ARTICLE, dbo.ARTICLE.GESTION_STOCK_BRF, dbo.ARTICLE.TYPE_DROIT_CONSOMMATION_ARTICLE, dbo.ARTICLE.VALEUR_DROIT_CONSOMMATION_ARTICLE, 
dbo.ARTICLE.DROIT_CONSOMMATION_VENTE_ARTICLE, dbo.ARTICLE.DROIT_CONSOMMATION_ACHAT_ARTICLE,
ARTICLE_PROPRIETE.TAILLE_ID,ARTICLE_PROPRIETE.COULEUR_ID,
TAILLE.NOM_TAILLE,COULEUR.NOM_COULEUR

FROM dbo.ARTICLE 
LEFT JOIN ARTICLE_PROPRIETE on ARTICLE_PROPRIETE.ARTICLE_ID=ARTICLE.ID_ARTICLE
LEFT JOIN TAILLE on TAILLE.ID_TAILLE=ARTICLE_PROPRIETE.TAILLE_ID
LEFT JOIN COULEUR on COULEUR.ID_COULEUR=ARTICLE_PROPRIETE.COULEUR_ID
LEFT JOIN STOCK_PROPRIETE on STOCK_PROPRIETE.ARTICLE_PROPRIETE_ID=ARTICLE.ID_ARTICLE 
and STOCK_PROPRIETE.TAILLE_PROPRIETE_ID=TAILLE.ID_TAILLE and STOCK_PROPRIETE.COULEUR_PROPRIETE_ID=COULEUR.ID_COULEUR 
LEFT OUTER JOIN dbo.FAMILLE_ARTICLE ON dbo.ARTICLE.FAMILLE_ARTICLE_ID = dbo.FAMILLE_ARTICLE.ID_FAMILLE_ARTICLE 
LEFT OUTER JOIN dbo.TVA_ARTICLE ON dbo.ARTICLE.TVA_ARTICLE_ID = dbo.TVA_ARTICLE.ID_TVA_ARTICLE 
LEFT OUTER JOIN dbo.MARQUE_ARTICLE ON dbo.ARTICLE.MARQUE_ARTICLE_ID = dbo.MARQUE_ARTICLE.ID_MARQUE_ARTICLE
LEFT OUTER JOIN dbo.CATEGORIE_ARTICLE ON dbo.ARTICLE.CATEGORIE_ARTICLE_ID = dbo.CATEGORIE_ARTICLE.ID_CATEGORIE_ARTICLE 
LEFT OUTER JOIN dbo.UNITE_ARTICLE ON dbo.ARTICLE.UNITE_ARTICLE_ID = dbo.UNITE_ARTICLE.ID_UNITE_ARTICLE 
LEFT OUTER JOIN dbo.DEPOT ON dbo.ARTICLE.DEPOT_ARTICLE_ID = dbo.DEPOT.ID_DEPOT
WHERE        (dbo.ARTICLE.DIVERS_ARTICLE = 0)
GO


---------------------------------------------------------------------------------------

IF OBJECT_ID('VUE_ARTICLE_DEVISE', 'V') IS NOT NULL  
    DROP VIEW VUE_ARTICLE_DEVISE;  
GO
CREATE VIEW [dbo].[VUE_ARTICLE_DEVISE]
as
SELECT A.ID_ARTICLE, A.CODE_ARTICLE, A.LIBELLE_ARTICLE, A.UNITE_ARTICLE_ID, U.NOM_UNITE_ARTICLE, D.PRIX_ACHAT_ARTICLE_HT_ARTICLE_L AS PRIX_ACHAT_ARTICLE_HT, NULL AS TVA_ARTICLE_ID, NULL 
AS TVA_ARTICLE_TVA, D.PRIX_VENTE_ARTICLE_HT_ARTICLE_L AS PRIX_VENTE_ARTICLE_HT, A.QUANTITE_STOCK, A.BLOQUE_ARTICLE, A.SOCIETE_ID, dbo.TVA_ARTICLE.TAUX_TVA_ARTICLE, V.ID_DEVISE, 
A.DEPOT_ARTICLE_ID, dbo.DEPOT.NOM_DEPOT, A.FODEC_ACHAT_ARTICLE, A.FODEC_VENTE_ARTICLE, A.QUANTITE_ARTICLE, CAST(0 AS bit) AS SELECTION_ARTICLE, A.POIDS_NET_KG, A.POIDS_BRUT_KG, 
A.TPE_ACHAT_ARTICLE, A.TPE_VENTE_ARTICLE, A.TYPE_DROIT_CONSOMMATION_ARTICLE, A.VALEUR_DROIT_CONSOMMATION_ARTICLE, A.DROIT_CONSOMMATION_ACHAT_ARTICLE, 
A.DROIT_CONSOMMATION_VENTE_ARTICLE
FROM dbo.ARTICLE AS A INNER JOIN
dbo.DEVISE AS V ON V.SOCIETE_ID=A.SOCIETE_ID INNER JOIN
dbo.DEPOT ON A.DEPOT_ARTICLE_ID = dbo.DEPOT.ID_DEPOT LEFT OUTER JOIN
dbo.TVA_ARTICLE ON A.TVA_ARTICLE_ID = dbo.TVA_ARTICLE.ID_TVA_ARTICLE LEFT OUTER JOIN
dbo.ARTICLE_DEVISE AS D ON A.ID_ARTICLE = D.ARTICLE_ID LEFT OUTER JOIN
dbo.UNITE_ARTICLE AS U ON U.ID_UNITE_ARTICLE = A.UNITE_ARTICLE_ID
GO


-----------------------------------------------------------------------------------------

update GRID_COLONNE set ORDRE_COLONNE=ORDRE_COLONNE+2 where GRID_ID=37 and ORDRE_COLONNE>=4

insert GRID_COLONNE  (ID_GRID_COLONNE,GRID_ID,CHAMPS_COLONNE,NOM_COLONNE,LISTE_COLONNE,VALEUR_DEFAUT_COLONNE,LARGEUR_COLONNE,CHECK_COLONNE,LONGUEUR_TYPE_COLONNE,ACTIF_COLONNE,VISIBLE_COLONNE,READONLY_COLONNE,MONNAIE_COLONNE,GRID_LISTE_COLONNE,CALCULE_COLONNE,TRONQUER_ZERO_COLONNE,ZERO_VIDE_COLONNE,ACCEPTER_NULL_COLONNE,VISIBLE_DEFAUT_COLONNE,ORDRE_COLONNE,TYPE_COLONNE,ALIGN_COLONNE) values (1770,'37','NOM_TAILLE','TAILLE',NULL,NULL,'80',NULL,'100','1','1','1','0','0','0','0','0','0','0','4','TEXT','C')
insert GRID_COLONNE  (ID_GRID_COLONNE,GRID_ID,CHAMPS_COLONNE,NOM_COLONNE,LISTE_COLONNE,VALEUR_DEFAUT_COLONNE,LARGEUR_COLONNE,CHECK_COLONNE,LONGUEUR_TYPE_COLONNE,ACTIF_COLONNE,VISIBLE_COLONNE,READONLY_COLONNE,MONNAIE_COLONNE,GRID_LISTE_COLONNE,CALCULE_COLONNE,TRONQUER_ZERO_COLONNE,ZERO_VIDE_COLONNE,ACCEPTER_NULL_COLONNE,VISIBLE_DEFAUT_COLONNE,ORDRE_COLONNE,TYPE_COLONNE,ALIGN_COLONNE) values (1771,'37','NOM_COULEUR','COULEUR',NULL,NULL,'80',NULL,'100','1','1','1','0','0','0','0','0','0','0','5','TEXT','C')



insert GRID_COLONNE  (ID_GRID_COLONNE,GRID_ID,CHAMPS_COLONNE,NOM_COLONNE,LISTE_COLONNE,VALEUR_DEFAUT_COLONNE,LARGEUR_COLONNE,CHECK_COLONNE,LONGUEUR_TYPE_COLONNE,
ACTIF_COLONNE,VISIBLE_COLONNE,READONLY_COLONNE,MONNAIE_COLONNE,GRID_LISTE_COLONNE,CALCULE_COLONNE,TRONQUER_ZERO_COLONNE,ZERO_VIDE_COLONNE,ACCEPTER_NULL_COLONNE,
VISIBLE_DEFAUT_COLONNE,ORDRE_COLONNE,TYPE_COLONNE,ALIGN_COLONNE)
values
(1799,'37','TAILLE_ID','TAILLE_ID',NULL,NULL,'0',NULL,'0','1','0','1','0','0','0','0','0','0','0','11','NUMERIC','L')
insert GRID_COLONNE  (ID_GRID_COLONNE,GRID_ID,CHAMPS_COLONNE,NOM_COLONNE,LISTE_COLONNE,VALEUR_DEFAUT_COLONNE,LARGEUR_COLONNE,CHECK_COLONNE,LONGUEUR_TYPE_COLONNE,
ACTIF_COLONNE,VISIBLE_COLONNE,READONLY_COLONNE,MONNAIE_COLONNE,GRID_LISTE_COLONNE,CALCULE_COLONNE,TRONQUER_ZERO_COLONNE,ZERO_VIDE_COLONNE,ACCEPTER_NULL_COLONNE,
VISIBLE_DEFAUT_COLONNE,ORDRE_COLONNE,TYPE_COLONNE,ALIGN_COLONNE)
values
(1800,'37','COULEUR_ID','COULEUR_ID',NULL,NULL,'0',NULL,'0','1','0','1','0','0','0','0','0','0','0','12','NUMERIC','L')

GO

update GRID_COLONNE set ORDRE_COLONNE=ORDRE_COLONNE+1 where GRID_ID=37

insert GRID_COLONNE  (ID_GRID_COLONNE,GRID_ID,CHAMPS_COLONNE,NOM_COLONNE,LISTE_COLONNE,VALEUR_DEFAUT_COLONNE,LARGEUR_COLONNE,CHECK_COLONNE,LONGUEUR_TYPE_COLONNE,ACTIF_COLONNE,VISIBLE_COLONNE,READONLY_COLONNE,MONNAIE_COLONNE,GRID_LISTE_COLONNE,CALCULE_COLONNE,TRONQUER_ZERO_COLONNE,ZERO_VIDE_COLONNE,ACCEPTER_NULL_COLONNE,VISIBLE_DEFAUT_COLONNE,ORDRE_COLONNE,TYPE_COLONNE,ALIGN_COLONNE) values (1772,'37','ROW_NUMBER() over(order by ID_ARTICLE)','ROW_INDEX',NULL,NULL,0,NULL,NULL,'1','0','0','0','0','0','0','0','0','0','1','NUMERIC','L')

GO

------------------------------------------------------------------------------------------