
IF OBJECT_ID('PRC_IMP_DOCUMENT_LIGNE') IS NOT NULL  
    DROP PROCEDURE PRC_IMP_DOCUMENT_LIGNE;  
GO
create procedure [dbo].[PRC_IMP_DOCUMENT_LIGNE] @ID_TYPE_DOCUMENT numeric(18,0),@ID_DOCUMENT numeric(18,0)
as
Begin

declare @sql as nvarchar(MAX)
declare @TABLE varchar(50)
declare @TABLE_LIGNE varchar(50)
declare @ABBREVIATION varchar(10)
declare @NOMBRE_DECIMAL int
declare @ID_DEVISE numeric(18,0)
declare @VA char(1)
declare @NUMERO_SERIE_TD bit
declare @ID_SOCIETE numeric(18,0)
declare @IMPRESSION_DOCUMENT_SOURCE bit

select @TABLE=TABLE_TD,@TABLE_LIGNE=TABLE_LIGNE_TD,@ABBREVIATION=ABBREVIATION_TD,
@VA=VA_TD,@NUMERO_SERIE_TD=NUMERO_SERIE_TD
from TYPE_DOCUMENT 
where ID_TD=@ID_TYPE_DOCUMENT

BEGIN TRY

set @sql='select @ID_DEVISE=DEVISE_'+@ABBREVIATION+'_ID,@ID_SOCIETE=SOCIETE_ID from '+@TABLE+' where ID_'+@ABBREVIATION+'='+CAST(@ID_DOCUMENT as varchar(50))
execute sp_executesql @sql,N'@ID_DEVISE numeric(18,0) output,@ID_SOCIETE numeric(18,0) output',@ID_DEVISE output,@ID_SOCIETE output

set @sql='select @NOMBRE_DECIMAL=NOMBRE_DECIMAL from VUE_DEVISE where ID_DEVISE='+CAST(@ID_DEVISE as varchar(50))
execute sp_executesql @sql,N'@NOMBRE_DECIMAL int output',@NOMBRE_DECIMAL output

set @sql='select @IMPRESSION_DOCUMENT_SOURCE=IMPRESSION_DOCUMENT_SOURCE from SOCIETE where ID_SOCIETE='+CAST(@ID_SOCIETE as varchar(50))
execute sp_executesql @sql,N'@IMPRESSION_DOCUMENT_SOURCE bit output',@IMPRESSION_DOCUMENT_SOURCE output


set @sql='select ARTICLE_CODE_'+@ABBREVIATION+'_L as ARTICLE_CODE, 
LIBELLE_ARTICLE_'+@ABBREVIATION+'_L'

if @NUMERO_SERIE_TD=1
	set @sql=@sql+'+CASE WHEN NUMERO_SERIE_'+@ABBREVIATION+'_L is not NULL and NUMERO_SERIE_'+@ABBREVIATION+'_L<>''''
	THEN char(10)+char(13)+''NS : ''+NUMERO_SERIE_'+@ABBREVIATION+'_L ELSE ''''  END'

if @IMPRESSION_DOCUMENT_SOURCE=1
	set @sql=@sql+'+CASE WHEN NUMERO_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L is not NULL and NUMERO_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L<>''''
	THEN char(10)+char(13)+''SOURCE : ''+NUMERO_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L ELSE ''''  END'

set @sql=@sql+' as LIBELLE_ARTICLE,
CAST(PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_HT_BRUT_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+'))as PRIX_ARTICLE_HT_BRUT ,
CASE WHEN TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L as float) END as TAUX_REMISE_ARTICLE,
CASE WHEN MONTANT_REMISE_ARTICLE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(MONTANT_REMISE_ARTICLE_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as MONTANT_REMISE_ARTICLE ,
CASE WHEN PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_HT_NET_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as PRIX_ARTICLE_HT_NET,
CAST(QTE_ARTICLE_'+@ABBREVIATION+'_L as float) as QTE_ARTICLE,
CASE WHEN TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(TOTAL_ARTICLE_HT_NET_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as MONTANT_HT,
CAST(TAUX_ARTICLE_TVA_'+@ABBREVIATION+'_L as float) as TAUX_ARTICLE_TVA,
CAST(TAUX_ARTICLE_TVA_ORIGINE_'+@ABBREVIATION+'_L as float) as TAUX_ARTICLE_TVA_ORIGINE,
CASE WHEN TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(TOTAL_ARTICLE_TTC_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as MONTANT_TTC,
CASE WHEN PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_TTC_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_TTC_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as PRIX_ARTICLE_TTC,
CAST(PRIX_VENTE_PUBLIC_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) as PRIX_VENTE_PUBLIC ,FODEC_'+@ABBREVIATION+'_L as FODEC'
set @sql=@sql+',NOM_UNITE_ARTICLE_'+@ABBREVIATION+'_L as UNITE_ARTICLE '
set @sql=@sql+',NOM_TAILLE_'+@ABBREVIATION+'_L as TAILLE '
set @sql=@sql+',NOM_COULEUR_'+@ABBREVIATION+'_L as COULEUR '
if @ID_TYPE_DOCUMENT=8 --FACTURE CLIENT
	Begin
		set @sql=@sql+',DATE_PROCES_VERBAL'
		set @sql=@sql+',NOMBRE_CARTON_FCC_L,FORMAT_CARTON_FCC_L'
	End

if @ID_TYPE_DOCUMENT=7 or @ID_TYPE_DOCUMENT=6 or @ID_TYPE_DOCUMENT=8 or @ID_TYPE_DOCUMENT=9
	set @sql=@sql+',DOCUMENT_DOUANE_BRF,FORMAT(DATE_BRF, ''dd/MM/yyyy'') as DATE_BRF'

if @NUMERO_SERIE_TD=1
	set @sql=@sql+',NUMERO_SERIE_'+@ABBREVIATION+'_L as NUMERO_SERIE_L '

set @sql=@sql+' from '+@TABLE_LIGNE
if @ID_TYPE_DOCUMENT=8 --FACTURE CLIENT
	set @sql=@sql+' inner join VUE_ARTICLE on VUE_ARTICLE.ID_ARTICLE=ARTICLE_FCC_L_ID'

if @ID_TYPE_DOCUMENT=7 or @ID_TYPE_DOCUMENT=6 or @ID_TYPE_DOCUMENT=8 or @ID_TYPE_DOCUMENT=9
	set @sql=@sql+' left join BON_RECEPTION_FOURNISSEUR on BON_RECEPTION_FOURNISSEUR.ID_BRF=BRF_'+@ABBREVIATION+'_L_ID '


set @sql=@sql+' where '+@ABBREVIATION+'_ID= '+CAST(@ID_DOCUMENT as varchar(50))
+'order by CASE WHEN TYPE_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L is NULL THEN 1 ELSE 0 END,
TYPE_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L,DOCUMENT_SOURCE_'+@ABBREVIATION+'_L_ID,ORDRE_'+@ABBREVIATION+'_L,ID_'+@ABBREVIATION+'_L '

execute sp_executesql @sql

END TRY
BEGIN CATCH  
	insert SQL_ERREUR (QUERY) values (@SQL)
	select -99,ERROR_NUMBER() 
	RETURN
END CATCH;  

End

GO


------------------------------------------------------------------------------
IF OBJECT_ID('PRC_IMP_DOCUMENT_LIGNE_SOCIETE') IS NOT NULL  
    DROP PROCEDURE PRC_IMP_DOCUMENT_LIGNE_SOCIETE;  
GO

create procedure [dbo].[PRC_IMP_DOCUMENT_LIGNE_SOCIETE] @ID_TYPE_DOCUMENT numeric(18,0),@ID_DOCUMENT numeric(18,0)
as
Begin

declare @sql as nvarchar(MAX)
declare @TABLE varchar(50)
declare @TABLE_LIGNE varchar(50)
declare @ABBREVIATION varchar(10)
declare @NOMBRE_DECIMAL int
declare @ID_SOCIETE numeric(18,0)
declare @VA char(1)
declare @NUMERO_SERIE_TD bit
declare @IMPRESSION_DOCUMENT_SOURCE bit

select @TABLE=TABLE_TD,@TABLE_LIGNE=TABLE_LIGNE_TD,@ABBREVIATION=ABBREVIATION_TD,
@VA=VA_TD,@NUMERO_SERIE_TD=NUMERO_SERIE_TD
from TYPE_DOCUMENT 
where ID_TD=@ID_TYPE_DOCUMENT

BEGIN TRY

set @sql='select @ID_SOCIETE=SOCIETE_ID from '+@TABLE+' where ID_'+@ABBREVIATION+'='+CAST(@ID_DOCUMENT as varchar(50))
execute sp_executesql @sql,N'@ID_SOCIETE numeric(18,0) output',@ID_SOCIETE output

set @sql='select @NOMBRE_DECIMAL=NOMBRE_DECIMAL from VUE_SOCIETE where ID_SOCIETE='+CAST(@ID_SOCIETE as varchar(50))
execute sp_executesql @sql,N'@NOMBRE_DECIMAL int output',@NOMBRE_DECIMAL output

set @sql='select @IMPRESSION_DOCUMENT_SOURCE=IMPRESSION_DOCUMENT_SOURCE from SOCIETE where ID_SOCIETE='+CAST(@ID_SOCIETE as varchar(50))
execute sp_executesql @sql,N'@IMPRESSION_DOCUMENT_SOURCE bit output',@IMPRESSION_DOCUMENT_SOURCE output

set @sql='select ARTICLE_CODE_'+@ABBREVIATION+'_L as ARTICLE_CODE, 
LIBELLE_ARTICLE_'+@ABBREVIATION+'_L'

if @NUMERO_SERIE_TD=1
	set @sql=@sql+'+CASE WHEN NUMERO_SERIE_'+@ABBREVIATION+'_L is not NULL and NUMERO_SERIE_'+@ABBREVIATION+'_L<>''''
	THEN char(10)+char(13)+''NS : ''+NUMERO_SERIE_'+@ABBREVIATION+'_L ELSE ''''  END'

if @IMPRESSION_DOCUMENT_SOURCE=1
	set @sql=@sql+'+CASE WHEN NUMERO_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L is not NULL and NUMERO_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L<>''''
	THEN char(10)+char(13)+''SOURCE : ''+NUMERO_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L ELSE ''''  END'

set @sql=@sql+' as LIBELLE_ARTICLE,
CAST(PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_HT_BRUT_DEVISE_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+'))as PRIX_ARTICLE_HT_BRUT ,
CASE WHEN TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(TAUX_REMISE_ARTICLE_'+@ABBREVIATION+'_L as float) END as TAUX_REMISE_ARTICLE,
CASE WHEN MONTANT_REMISE_ARTICLE_DEVISE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(MONTANT_REMISE_ARTICLE_DEVISE_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as MONTANT_REMISE_ARTICLE ,
CASE WHEN PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_HT_NET_DEVISE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_HT_NET_DEVISE_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as PRIX_ARTICLE_HT_NET,
CAST(QTE_ARTICLE_'+@ABBREVIATION+'_L as float) as QTE_ARTICLE,
CASE WHEN TOTAL_ARTICLE_HT_NET_DEVISE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(TOTAL_ARTICLE_HT_NET_DEVISE_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as MONTANT_HT,
CAST(TAUX_ARTICLE_TVA_'+@ABBREVIATION+'_L as float) as TAUX_ARTICLE_TVA,
CASE WHEN TOTAL_ARTICLE_TTC_DEVISE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(TOTAL_ARTICLE_TTC_DEVISE_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as MONTANT_TTC,
CASE WHEN PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_TTC_DEVISE_'+@ABBREVIATION+'_L=0 THEN NULL ELSE CAST(PRIX_'+CASE WHEN @VA='V' THEN 'VENTE' ELSE 'ACHAT' END+'_ARTICLE_TTC_DEVISE_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) END as PRIX_ARTICLE_TTC,
CAST(PRIX_VENTE_PUBLIC_'+@ABBREVIATION+'_L as decimal(18,'+CAST(@NOMBRE_DECIMAL as varchar(50))+')) as PRIX_VENTE_PUBLIC '
set @sql=@sql+',NOM_UNITE_ARTICLE_'+@ABBREVIATION+'_L as UNITE_ARTICLE '
set @sql=@sql+',NOM_TAILLE_'+@ABBREVIATION+'_L as TAILLE '
set @sql=@sql+',NOM_COULEUR_'+@ABBREVIATION+'_L as COULEUR '

if @ID_TYPE_DOCUMENT=8 --FACTURE CLIENT
	Begin
		set @sql=@sql+',DATE_PROCES_VERBAL'
		set @sql=@sql+',NOMBRE_CARTON_FCC_L,FORMAT_CARTON_FCC_L,NOM_FAMILLE_ARTICLE'
	End

if @ID_TYPE_DOCUMENT=3 or @ID_TYPE_DOCUMENT=6 or @ID_TYPE_DOCUMENT=8
	set @sql=@sql+',DOCUMENT_DOUANE_BRF,FORMAT(DATE_BRF, ''dd/MM/yyyy'') as DATE_BRF'

if @NUMERO_SERIE_TD=1
	set @sql=@sql+',NUMERO_SERIE_'+@ABBREVIATION+'_L as NUMERO_SERIE_L '

set @sql=@sql+' from '+@TABLE_LIGNE

if @ID_TYPE_DOCUMENT=8 --FACTURE CLIENT
	set @sql=@sql+' inner join VUE_ARTICLE on VUE_ARTICLE.ID_ARTICLE=ARTICLE_FCC_L_ID'

if @ID_TYPE_DOCUMENT=3 or @ID_TYPE_DOCUMENT=6 or @ID_TYPE_DOCUMENT=8
	set @sql=@sql+' left join BON_RECEPTION_FOURNISSEUR on BON_RECEPTION_FOURNISSEUR.ID_BRF=BRF_'+@ABBREVIATION+'_L_ID '

set @sql=@sql+' where '+@ABBREVIATION+'_ID= '+CAST(@ID_DOCUMENT as varchar(50))
+'order by CASE WHEN TYPE_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L is NULL THEN 1 ELSE 0 END,
TYPE_DOCUMENT_SOURCE_'+@ABBREVIATION+'_L,DOCUMENT_SOURCE_'+@ABBREVIATION+'_L_ID,ORDRE_'+@ABBREVIATION+'_L,ID_'+@ABBREVIATION+'_L '
execute sp_executesql @sql

END TRY
BEGIN CATCH  
	insert SQL_ERREUR (QUERY) values (@SQL)
	select -99,ERROR_NUMBER() 
	RETURN
END CATCH;  

End

GO

-----------------------------------------------------------------------------

